/* tslint:disable */
/* eslint-disable */
/**
 * service-danmaku
 * 弹幕服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatRoom
 */
export interface ChatRoom {
    /**
     * 
     * @type {number}
     * @memberof ChatRoom
     */
    chatId?: number;
    /**
     * 
     * @type {number}
     * @memberof ChatRoom
     */
    videoId?: number;
    /**
     * 
     * @type {Date}
     * @memberof ChatRoom
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the ChatRoom interface.
 */
export function instanceOfChatRoom(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChatRoomFromJSON(json: any): ChatRoom {
    return ChatRoomFromJSONTyped(json, false);
}

export function ChatRoomFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatRoom {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chatId': !exists(json, 'chatId') ? undefined : json['chatId'],
        'videoId': !exists(json, 'videoId') ? undefined : json['videoId'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function ChatRoomToJSON(value?: ChatRoom | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chatId': value.chatId,
        'videoId': value.videoId,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

