/* tslint:disable */
/* eslint-disable */
/**
 * service-danmaku
 * 弹幕服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessage
 */
export interface ChatMessage {
    /**
     * 
     * @type {number}
     * @memberof ChatMessage
     */
    messageId: number;
    /**
     * 
     * @type {number}
     * @memberof ChatMessage
     */
    chatId: number;
    /**
     * 
     * @type {number}
     * @memberof ChatMessage
     */
    progress: number;
    /**
     * 
     * @type {number}
     * @memberof ChatMessage
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof ChatMessage
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof ChatMessage
     */
    messageType: number;
    /**
     * 
     * @type {number}
     * @memberof ChatMessage
     */
    colorHex: number;
    /**
     * 
     * @type {Date}
     * @memberof ChatMessage
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ChatMessage interface.
 */
export function instanceOfChatMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "messageId" in value;
    isInstance = isInstance && "chatId" in value;
    isInstance = isInstance && "progress" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "messageType" in value;
    isInstance = isInstance && "colorHex" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function ChatMessageFromJSON(json: any): ChatMessage {
    return ChatMessageFromJSONTyped(json, false);
}

export function ChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'messageId': json['messageId'],
        'chatId': json['chatId'],
        'progress': json['progress'],
        'userId': json['userId'],
        'content': json['content'],
        'messageType': json['messageType'],
        'colorHex': json['colorHex'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ChatMessageToJSON(value?: ChatMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'messageId': value.messageId,
        'chatId': value.chatId,
        'progress': value.progress,
        'userId': value.userId,
        'content': value.content,
        'messageType': value.messageType,
        'colorHex': value.colorHex,
        'createdAt': (value.createdAt.toISOString()),
    };
}

