/* tslint:disable */
/* eslint-disable */
/**
 * service-danmaku
 * 弹幕服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
} from './ChatMessage';

/**
 * 
 * @export
 * @interface ResponseListChatMessage
 */
export interface ResponseListChatMessage {
    /**
     * 
     * @type {number}
     * @memberof ResponseListChatMessage
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseListChatMessage
     */
    message?: string;
    /**
     * 
     * @type {Array<ChatMessage>}
     * @memberof ResponseListChatMessage
     */
    data?: Array<ChatMessage>;
}

/**
 * Check if a given object implements the ResponseListChatMessage interface.
 */
export function instanceOfResponseListChatMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseListChatMessageFromJSON(json: any): ResponseListChatMessage {
    return ResponseListChatMessageFromJSONTyped(json, false);
}

export function ResponseListChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListChatMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ChatMessageFromJSON)),
    };
}

export function ResponseListChatMessageToJSON(value?: ResponseListChatMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ChatMessageToJSON)),
    };
}

