/* tslint:disable */
/* eslint-disable */
/**
 * service-danmaku
 * 弹幕服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChatRoom } from './ChatRoom';
import {
    ChatRoomFromJSON,
    ChatRoomFromJSONTyped,
    ChatRoomToJSON,
} from './ChatRoom';

/**
 * 
 * @export
 * @interface ResponseChatRoom
 */
export interface ResponseChatRoom {
    /**
     * 
     * @type {number}
     * @memberof ResponseChatRoom
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseChatRoom
     */
    message?: string;
    /**
     * 
     * @type {ChatRoom}
     * @memberof ResponseChatRoom
     */
    data?: ChatRoom;
}

/**
 * Check if a given object implements the ResponseChatRoom interface.
 */
export function instanceOfResponseChatRoom(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseChatRoomFromJSON(json: any): ResponseChatRoom {
    return ResponseChatRoomFromJSONTyped(json, false);
}

export function ResponseChatRoomFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseChatRoom {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ChatRoomFromJSON(json['data']),
    };
}

export function ResponseChatRoomToJSON(value?: ResponseChatRoom | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': ChatRoomToJSON(value.data),
    };
}

