/* tslint:disable */
/* eslint-disable */
/**
 * service-danmaku
 * 弹幕服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
} from './ChatMessage';

/**
 * 
 * @export
 * @interface ResponseChatMessage
 */
export interface ResponseChatMessage {
    /**
     * 
     * @type {number}
     * @memberof ResponseChatMessage
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseChatMessage
     */
    message?: string;
    /**
     * 
     * @type {ChatMessage}
     * @memberof ResponseChatMessage
     */
    data?: ChatMessage;
}

/**
 * Check if a given object implements the ResponseChatMessage interface.
 */
export function instanceOfResponseChatMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseChatMessageFromJSON(json: any): ResponseChatMessage {
    return ResponseChatMessageFromJSONTyped(json, false);
}

export function ResponseChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseChatMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ChatMessageFromJSON(json['data']),
    };
}

export function ResponseChatMessageToJSON(value?: ResponseChatMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': ChatMessageToJSON(value.data),
    };
}

