/* tslint:disable */
/* eslint-disable */
/**
 * service-danmaku
 * 弹幕服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendDanmakuDTO
 */
export interface SendDanmakuDTO {
    /**
     * 
     * @type {number}
     * @memberof SendDanmakuDTO
     */
    chatRoomId?: number;
    /**
     * 
     * @type {number}
     * @memberof SendDanmakuDTO
     */
    time?: number;
    /**
     * 
     * @type {string}
     * @memberof SendDanmakuDTO
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof SendDanmakuDTO
     */
    color?: number;
    /**
     * 
     * @type {number}
     * @memberof SendDanmakuDTO
     */
    type?: number;
    /**
     * 
     * @type {number}
     * @memberof SendDanmakuDTO
     */
    fontSize?: number;
}

/**
 * Check if a given object implements the SendDanmakuDTO interface.
 */
export function instanceOfSendDanmakuDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SendDanmakuDTOFromJSON(json: any): SendDanmakuDTO {
    return SendDanmakuDTOFromJSONTyped(json, false);
}

export function SendDanmakuDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendDanmakuDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chatRoomId': !exists(json, 'chatRoomId') ? undefined : json['chatRoomId'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'fontSize': !exists(json, 'fontSize') ? undefined : json['fontSize'],
    };
}

export function SendDanmakuDTOToJSON(value?: SendDanmakuDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chatRoomId': value.chatRoomId,
        'time': value.time,
        'content': value.content,
        'color': value.color,
        'type': value.type,
        'fontSize': value.fontSize,
    };
}

