/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UpdateVideoResourceConversionStateDTO,
  VideoPostDTO,
} from '../models/index';
import {
    UpdateVideoResourceConversionStateDTOFromJSON,
    UpdateVideoResourceConversionStateDTOToJSON,
    VideoPostDTOFromJSON,
    VideoPostDTOToJSON,
} from '../models/index';

export interface GetVideoPostRequest {
    nkid: number;
    viewerUserId: number;
}

export interface GetVideoPostBatchRequest {
    nkidList: Array<number>;
    viewerUserId: number;
}

export interface UpdateVideoResourceRequest {
    videoId: number;
    dashMpdUrl: number;
}

export interface UpdateVideoResourceConversionStateRequest {
    updateVideoResourceConversionStateDTO: UpdateVideoResourceConversionStateDTO;
}

/**
 * 
 */
export class VideoInternalControllerApi extends runtime.BaseAPI {

    /**
     */
    async getVideoPostRaw(requestParameters: GetVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoPostDTO>> {
        if (requestParameters.nkid === null || requestParameters.nkid === undefined) {
            throw new runtime.RequiredError('nkid','Required parameter requestParameters.nkid was null or undefined when calling getVideoPost.');
        }

        if (requestParameters.viewerUserId === null || requestParameters.viewerUserId === undefined) {
            throw new runtime.RequiredError('viewerUserId','Required parameter requestParameters.viewerUserId was null or undefined when calling getVideoPost.');
        }

        const queryParameters: any = {};

        if (requestParameters.nkid !== undefined) {
            queryParameters['nkid'] = requestParameters.nkid;
        }

        if (requestParameters.viewerUserId !== undefined) {
            queryParameters['viewerUserId'] = requestParameters.viewerUserId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/internal/video/getVideoPost`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoPostDTOFromJSON(jsonValue));
    }

    /**
     */
    async getVideoPost(requestParameters: GetVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoPostDTO> {
        const response = await this.getVideoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getVideoPostBatchRaw(requestParameters: GetVideoPostBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: VideoPostDTO; }>> {
        if (requestParameters.nkidList === null || requestParameters.nkidList === undefined) {
            throw new runtime.RequiredError('nkidList','Required parameter requestParameters.nkidList was null or undefined when calling getVideoPostBatch.');
        }

        if (requestParameters.viewerUserId === null || requestParameters.viewerUserId === undefined) {
            throw new runtime.RequiredError('viewerUserId','Required parameter requestParameters.viewerUserId was null or undefined when calling getVideoPostBatch.');
        }

        const queryParameters: any = {};

        if (requestParameters.nkidList) {
            queryParameters['nkidList'] = requestParameters.nkidList;
        }

        if (requestParameters.viewerUserId !== undefined) {
            queryParameters['viewerUserId'] = requestParameters.viewerUserId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/internal/video/getVideoPostBatch`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, VideoPostDTOFromJSON));
    }

    /**
     */
    async getVideoPostBatch(requestParameters: GetVideoPostBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: VideoPostDTO; }> {
        const response = await this.getVideoPostBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新视频资源信息
     */
    async updateVideoResourceRaw(requestParameters: UpdateVideoResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.videoId === null || requestParameters.videoId === undefined) {
            throw new runtime.RequiredError('videoId','Required parameter requestParameters.videoId was null or undefined when calling updateVideoResource.');
        }

        if (requestParameters.dashMpdUrl === null || requestParameters.dashMpdUrl === undefined) {
            throw new runtime.RequiredError('dashMpdUrl','Required parameter requestParameters.dashMpdUrl was null or undefined when calling updateVideoResource.');
        }

        const queryParameters: any = {};

        if (requestParameters.videoId !== undefined) {
            queryParameters['videoId'] = requestParameters.videoId;
        }

        if (requestParameters.dashMpdUrl !== undefined) {
            queryParameters['dashMpdUrl'] = requestParameters.dashMpdUrl;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/internal/video/internal/video/updateVideoResource`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 更新视频资源信息
     */
    async updateVideoResource(requestParameters: UpdateVideoResourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateVideoResourceRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateVideoResourceConversionStateRaw(requestParameters: UpdateVideoResourceConversionStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.updateVideoResourceConversionStateDTO === null || requestParameters.updateVideoResourceConversionStateDTO === undefined) {
            throw new runtime.RequiredError('updateVideoResourceConversionStateDTO','Required parameter requestParameters.updateVideoResourceConversionStateDTO was null or undefined when calling updateVideoResourceConversionState.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/internal/video/updateVideoResourceConversionState`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateVideoResourceConversionStateDTOToJSON(requestParameters.updateVideoResourceConversionStateDTO),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateVideoResourceConversionState(requestParameters: UpdateVideoResourceConversionStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateVideoResourceConversionStateRaw(requestParameters, initOverrides);
    }

}
