/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddTagDto,
  CreateVideoPostDto,
  ResponseCreateVideoPostVo,
  ResponseListPartitionInfo,
  ResponseListPartitionRecommendTag,
  ResponseString,
  ResponseTag,
  ResponseVideoPostBriefVo,
} from '../models/index';
import {
    AddTagDtoFromJSON,
    AddTagDtoToJSON,
    CreateVideoPostDtoFromJSON,
    CreateVideoPostDtoToJSON,
    ResponseCreateVideoPostVoFromJSON,
    ResponseCreateVideoPostVoToJSON,
    ResponseListPartitionInfoFromJSON,
    ResponseListPartitionInfoToJSON,
    ResponseListPartitionRecommendTagFromJSON,
    ResponseListPartitionRecommendTagToJSON,
    ResponseStringFromJSON,
    ResponseStringToJSON,
    ResponseTagFromJSON,
    ResponseTagToJSON,
    ResponseVideoPostBriefVoFromJSON,
    ResponseVideoPostBriefVoToJSON,
} from '../models/index';

export interface AddTagRequest {
    addTagDto: AddTagDto;
}

export interface CreateVideoPostRequest {
    createVideoPostDto: CreateVideoPostDto;
}

export interface GetPartitionRecommendTagListRequest {
    partitionId: number;
}

export interface GetVideoPostBriefRequest {
    nkid: number;
}

/**
 * 
 */
export class VideoControllerApi extends runtime.BaseAPI {

    /**
     * 添加标签
     */
    async addTagRaw(requestParameters: AddTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseTag>> {
        if (requestParameters.addTagDto === null || requestParameters.addTagDto === undefined) {
            throw new runtime.RequiredError('addTagDto','Required parameter requestParameters.addTagDto was null or undefined when calling addTag.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/video/video/addTag`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddTagDtoToJSON(requestParameters.addTagDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseTagFromJSON(jsonValue));
    }

    /**
     * 添加标签
     */
    async addTag(requestParameters: AddTagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseTag> {
        const response = await this.addTagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 创建视频投稿
     */
    async createVideoPostRaw(requestParameters: CreateVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseCreateVideoPostVo>> {
        if (requestParameters.createVideoPostDto === null || requestParameters.createVideoPostDto === undefined) {
            throw new runtime.RequiredError('createVideoPostDto','Required parameter requestParameters.createVideoPostDto was null or undefined when calling createVideoPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/video/video/createVideoPost`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateVideoPostDtoToJSON(requestParameters.createVideoPostDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseCreateVideoPostVoFromJSON(jsonValue));
    }

    /**
     * 创建视频投稿
     */
    async createVideoPost(requestParameters: CreateVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseCreateVideoPostVo> {
        const response = await this.createVideoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 生成用于封面上传的预签名链接。需要登录。使用返回的链接进行文件上传，请求方法为PUT，body为文件内容。
     * 生成封面上传链接
     */
    async generateCoverUploadUrlRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseString>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/video/video/generateCoverUploadUrl`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseStringFromJSON(jsonValue));
    }

    /**
     * 生成用于封面上传的预签名链接。需要登录。使用返回的链接进行文件上传，请求方法为PUT，body为文件内容。
     * 生成封面上传链接
     */
    async generateCoverUploadUrl(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseString> {
        const response = await this.generateCoverUploadUrlRaw(initOverrides);
        return await response.value();
    }

    /**
     * 生成用于上传视频文件的预签名链接。需要登录。使用返回的链接进行文件上传，请求方法为PUT，body为文件内容。
     * 生成视频上传链接
     */
    async generateUploadUrlRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseString>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/video/video/generateUploadUrl`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseStringFromJSON(jsonValue));
    }

    /**
     * 生成用于上传视频文件的预签名链接。需要登录。使用返回的链接进行文件上传，请求方法为PUT，body为文件内容。
     * 生成视频上传链接
     */
    async generateUploadUrl(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseString> {
        const response = await this.generateUploadUrlRaw(initOverrides);
        return await response.value();
    }

    /**
     * 查询所有的分区
     */
    async getPartitionListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseListPartitionInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/video/video/getPartitionList`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseListPartitionInfoFromJSON(jsonValue));
    }

    /**
     * 查询所有的分区
     */
    async getPartitionList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseListPartitionInfo> {
        const response = await this.getPartitionListRaw(initOverrides);
        return await response.value();
    }

    /**
     * 查询指定分区的推荐标签
     */
    async getPartitionRecommendTagListRaw(requestParameters: GetPartitionRecommendTagListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseListPartitionRecommendTag>> {
        if (requestParameters.partitionId === null || requestParameters.partitionId === undefined) {
            throw new runtime.RequiredError('partitionId','Required parameter requestParameters.partitionId was null or undefined when calling getPartitionRecommendTagList.');
        }

        const queryParameters: any = {};

        if (requestParameters.partitionId !== undefined) {
            queryParameters['partitionId'] = requestParameters.partitionId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/video/video/getPartitionRecommendTagList`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseListPartitionRecommendTagFromJSON(jsonValue));
    }

    /**
     * 查询指定分区的推荐标签
     */
    async getPartitionRecommendTagList(requestParameters: GetPartitionRecommendTagListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseListPartitionRecommendTag> {
        const response = await this.getPartitionRecommendTagListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 查询视频信息
     */
    async getVideoPostBriefRaw(requestParameters: GetVideoPostBriefRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseVideoPostBriefVo>> {
        if (requestParameters.nkid === null || requestParameters.nkid === undefined) {
            throw new runtime.RequiredError('nkid','Required parameter requestParameters.nkid was null or undefined when calling getVideoPostBrief.');
        }

        const queryParameters: any = {};

        if (requestParameters.nkid !== undefined) {
            queryParameters['nkid'] = requestParameters.nkid;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/video/video/getVideoPostBrief`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseVideoPostBriefVoFromJSON(jsonValue));
    }

    /**
     * 查询视频信息
     */
    async getVideoPostBrief(requestParameters: GetVideoPostBriefRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseVideoPostBriefVo> {
        const response = await this.getVideoPostBriefRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
