/* tslint:disable */
/* eslint-disable */
/**
 * service-comment
 * 评论服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommentPageVO,
  CommentVO,
  CreateCommentDTO,
  SecondaryCommentPageVO,
} from '../models/index';
import {
    CommentPageVOFromJSON,
    CommentPageVOToJSON,
    CommentVOFromJSON,
    CommentVOToJSON,
    CreateCommentDTOFromJSON,
    CreateCommentDTOToJSON,
    SecondaryCommentPageVOFromJSON,
    SecondaryCommentPageVOToJSON,
} from '../models/index';

export interface AddCommentRequest {
    createCommentDTO: CreateCommentDTO;
}

export interface DeleteCommentRequest {
    commentId: number;
}

export interface GetCommentRequest {
    objectId: number;
    idType: GetCommentIdTypeEnum;
    page?: number;
    size?: number;
}

export interface GetReplyCommentsRequest {
    rootCommentId: number;
    page?: number;
    size?: number;
}

export interface LikeCommentRequest {
    commentId: number;
}

export interface UnlikeCommentRequest {
    commentId: number;
}

/**
 * 
 */
export class CommentControllerApi extends runtime.BaseAPI {

    /**
     * 添加评论
     */
    async addCommentRaw(requestParameters: AddCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentVO>> {
        if (requestParameters.createCommentDTO === null || requestParameters.createCommentDTO === undefined) {
            throw new runtime.RequiredError('createCommentDTO','Required parameter requestParameters.createCommentDTO was null or undefined when calling addComment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/comment/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCommentDTOToJSON(requestParameters.createCommentDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentVOFromJSON(jsonValue));
    }

    /**
     * 添加评论
     */
    async addComment(requestParameters: AddCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentVO> {
        const response = await this.addCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 删除评论
     */
    async deleteCommentRaw(requestParameters: DeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.commentId === null || requestParameters.commentId === undefined) {
            throw new runtime.RequiredError('commentId','Required parameter requestParameters.commentId was null or undefined when calling deleteComment.');
        }

        const queryParameters: any = {};

        if (requestParameters.commentId !== undefined) {
            queryParameters['commentId'] = requestParameters.commentId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/comment/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 删除评论
     */
    async deleteComment(requestParameters: DeleteCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCommentRaw(requestParameters, initOverrides);
    }

    /**
     * 获取对象ID的评论列表
     */
    async getCommentRaw(requestParameters: GetCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentPageVO>> {
        if (requestParameters.objectId === null || requestParameters.objectId === undefined) {
            throw new runtime.RequiredError('objectId','Required parameter requestParameters.objectId was null or undefined when calling getComment.');
        }

        if (requestParameters.idType === null || requestParameters.idType === undefined) {
            throw new runtime.RequiredError('idType','Required parameter requestParameters.idType was null or undefined when calling getComment.');
        }

        const queryParameters: any = {};

        if (requestParameters.objectId !== undefined) {
            queryParameters['objectId'] = requestParameters.objectId;
        }

        if (requestParameters.idType !== undefined) {
            queryParameters['idType'] = requestParameters.idType;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/comment/getComments`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentPageVOFromJSON(jsonValue));
    }

    /**
     * 获取对象ID的评论列表
     */
    async getComment(requestParameters: GetCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentPageVO> {
        const response = await this.getCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 获取根评论的回复评论列表
     */
    async getReplyCommentsRaw(requestParameters: GetReplyCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SecondaryCommentPageVO>> {
        if (requestParameters.rootCommentId === null || requestParameters.rootCommentId === undefined) {
            throw new runtime.RequiredError('rootCommentId','Required parameter requestParameters.rootCommentId was null or undefined when calling getReplyComments.');
        }

        const queryParameters: any = {};

        if (requestParameters.rootCommentId !== undefined) {
            queryParameters['rootCommentId'] = requestParameters.rootCommentId;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/comment/getReplyComments`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SecondaryCommentPageVOFromJSON(jsonValue));
    }

    /**
     * 获取根评论的回复评论列表
     */
    async getReplyComments(requestParameters: GetReplyCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SecondaryCommentPageVO> {
        const response = await this.getReplyCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 点赞评论
     */
    async likeCommentRaw(requestParameters: LikeCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.commentId === null || requestParameters.commentId === undefined) {
            throw new runtime.RequiredError('commentId','Required parameter requestParameters.commentId was null or undefined when calling likeComment.');
        }

        const queryParameters: any = {};

        if (requestParameters.commentId !== undefined) {
            queryParameters['commentId'] = requestParameters.commentId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/comment/like`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 点赞评论
     */
    async likeComment(requestParameters: LikeCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.likeCommentRaw(requestParameters, initOverrides);
    }

    /**
     * 取消点赞评论
     */
    async unlikeCommentRaw(requestParameters: UnlikeCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.commentId === null || requestParameters.commentId === undefined) {
            throw new runtime.RequiredError('commentId','Required parameter requestParameters.commentId was null or undefined when calling unlikeComment.');
        }

        const queryParameters: any = {};

        if (requestParameters.commentId !== undefined) {
            queryParameters['commentId'] = requestParameters.commentId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/comment/unlike`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 取消点赞评论
     */
    async unlikeComment(requestParameters: UnlikeCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unlikeCommentRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const GetCommentIdTypeEnum = {
    Video: 'VIDEO',
    Activity: 'ACTIVITY'
} as const;
export type GetCommentIdTypeEnum = typeof GetCommentIdTypeEnum[keyof typeof GetCommentIdTypeEnum];
