/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddTagDto
 */
export interface AddTagDto {
    /**
     * 
     * @type {number}
     * @memberof AddTagDto
     */
    partitionId: number;
    /**
     * 
     * @type {string}
     * @memberof AddTagDto
     */
    name: string;
}

/**
 * Check if a given object implements the AddTagDto interface.
 */
export function instanceOfAddTagDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "partitionId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function AddTagDtoFromJSON(json: any): AddTagDto {
    return AddTagDtoFromJSONTyped(json, false);
}

export function AddTagDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTagDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'partitionId': json['partitionId'],
        'name': json['name'],
    };
}

export function AddTagDtoToJSON(value?: AddTagDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'partitionId': value.partitionId,
        'name': value.name,
    };
}

