/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateVideoPostVo
 */
export interface CreateVideoPostVo {
    /**
     * 
     * @type {number}
     * @memberof CreateVideoPostVo
     */
    nkid?: number;
}

/**
 * Check if a given object implements the CreateVideoPostVo interface.
 */
export function instanceOfCreateVideoPostVo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateVideoPostVoFromJSON(json: any): CreateVideoPostVo {
    return CreateVideoPostVoFromJSONTyped(json, false);
}

export function CreateVideoPostVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVideoPostVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nkid': !exists(json, 'nkid') ? undefined : json['nkid'],
    };
}

export function CreateVideoPostVoToJSON(value?: CreateVideoPostVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nkid': value.nkid,
    };
}

