/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateVideoPostDTO
 */
export interface CreateVideoPostDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateVideoPostDTO
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVideoPostDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVideoPostDTO
     */
    coverUrl: string;
    /**
     * 
     * @type {number}
     * @memberof CreateVideoPostDTO
     */
    partitionId: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateVideoPostDTO
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateVideoPostDTO
     */
    videoUrl: string;
}

/**
 * Check if a given object implements the CreateVideoPostDTO interface.
 */
export function instanceOfCreateVideoPostDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "coverUrl" in value;
    isInstance = isInstance && "partitionId" in value;
    isInstance = isInstance && "tags" in value;
    isInstance = isInstance && "videoUrl" in value;

    return isInstance;
}

export function CreateVideoPostDTOFromJSON(json: any): CreateVideoPostDTO {
    return CreateVideoPostDTOFromJSONTyped(json, false);
}

export function CreateVideoPostDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVideoPostDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'coverUrl': json['coverUrl'],
        'partitionId': json['partitionId'],
        'tags': json['tags'],
        'videoUrl': json['videoUrl'],
    };
}

export function CreateVideoPostDTOToJSON(value?: CreateVideoPostDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'coverUrl': value.coverUrl,
        'partitionId': value.partitionId,
        'tags': value.tags,
        'videoUrl': value.videoUrl,
    };
}

