/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateVideoPostDto
 */
export interface CreateVideoPostDto {
    /**
     * 
     * @type {string}
     * @memberof CreateVideoPostDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVideoPostDto
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateVideoPostDto
     */
    coverUrl: string;
    /**
     * 
     * @type {number}
     * @memberof CreateVideoPostDto
     */
    partitionId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateVideoPostDto
     */
    tagIds: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof CreateVideoPostDto
     */
    videoUrl: string;
}

/**
 * Check if a given object implements the CreateVideoPostDto interface.
 */
export function instanceOfCreateVideoPostDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "coverUrl" in value;
    isInstance = isInstance && "partitionId" in value;
    isInstance = isInstance && "tagIds" in value;
    isInstance = isInstance && "videoUrl" in value;

    return isInstance;
}

export function CreateVideoPostDtoFromJSON(json: any): CreateVideoPostDto {
    return CreateVideoPostDtoFromJSONTyped(json, false);
}

export function CreateVideoPostDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateVideoPostDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'coverUrl': json['coverUrl'],
        'partitionId': json['partitionId'],
        'tagIds': json['tagIds'],
        'videoUrl': json['videoUrl'],
    };
}

export function CreateVideoPostDtoToJSON(value?: CreateVideoPostDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'coverUrl': value.coverUrl,
        'partitionId': value.partitionId,
        'tagIds': value.tagIds,
        'videoUrl': value.videoUrl,
    };
}

