/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartitionRecommendTag
 */
export interface PartitionRecommendTag {
    /**
     * 
     * @type {number}
     * @memberof PartitionRecommendTag
     */
    partitionId?: number;
    /**
     * 
     * @type {string}
     * @memberof PartitionRecommendTag
     */
    name?: string;
}

/**
 * Check if a given object implements the PartitionRecommendTag interface.
 */
export function instanceOfPartitionRecommendTag(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PartitionRecommendTagFromJSON(json: any): PartitionRecommendTag {
    return PartitionRecommendTagFromJSONTyped(json, false);
}

export function PartitionRecommendTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartitionRecommendTag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'partitionId': !exists(json, 'partitionId') ? undefined : json['partitionId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function PartitionRecommendTagToJSON(value?: PartitionRecommendTag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'partitionId': value.partitionId,
        'name': value.name,
    };
}

