/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
} from './Tag';

/**
 * 
 * @export
 * @interface ResponseTag
 */
export interface ResponseTag {
    /**
     * 
     * @type {number}
     * @memberof ResponseTag
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseTag
     */
    message?: string;
    /**
     * 
     * @type {Tag}
     * @memberof ResponseTag
     */
    data?: Tag;
}

/**
 * Check if a given object implements the ResponseTag interface.
 */
export function instanceOfResponseTag(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseTagFromJSON(json: any): ResponseTag {
    return ResponseTagFromJSONTyped(json, false);
}

export function ResponseTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseTag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : TagFromJSON(json['data']),
    };
}

export function ResponseTagToJSON(value?: ResponseTag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': TagToJSON(value.data),
    };
}

