/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseListString
 */
export interface ResponseListString {
    /**
     * 
     * @type {number}
     * @memberof ResponseListString
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseListString
     */
    message?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ResponseListString
     */
    data?: Array<string>;
}

/**
 * Check if a given object implements the ResponseListString interface.
 */
export function instanceOfResponseListString(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseListStringFromJSON(json: any): ResponseListString {
    return ResponseListStringFromJSONTyped(json, false);
}

export function ResponseListStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListString {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function ResponseListStringToJSON(value?: ResponseListString | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': value.data,
    };
}

