/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserUploadedVideoStatisticsVO } from './UserUploadedVideoStatisticsVO';
import {
    UserUploadedVideoStatisticsVOFromJSON,
    UserUploadedVideoStatisticsVOFromJSONTyped,
    UserUploadedVideoStatisticsVOToJSON,
} from './UserUploadedVideoStatisticsVO';

/**
 * 
 * @export
 * @interface ResponseListUserUploadedVideoStatisticsVO
 */
export interface ResponseListUserUploadedVideoStatisticsVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseListUserUploadedVideoStatisticsVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseListUserUploadedVideoStatisticsVO
     */
    message?: string;
    /**
     * 
     * @type {Array<UserUploadedVideoStatisticsVO>}
     * @memberof ResponseListUserUploadedVideoStatisticsVO
     */
    data?: Array<UserUploadedVideoStatisticsVO>;
}

/**
 * Check if a given object implements the ResponseListUserUploadedVideoStatisticsVO interface.
 */
export function instanceOfResponseListUserUploadedVideoStatisticsVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseListUserUploadedVideoStatisticsVOFromJSON(json: any): ResponseListUserUploadedVideoStatisticsVO {
    return ResponseListUserUploadedVideoStatisticsVOFromJSONTyped(json, false);
}

export function ResponseListUserUploadedVideoStatisticsVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListUserUploadedVideoStatisticsVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(UserUploadedVideoStatisticsVOFromJSON)),
    };
}

export function ResponseListUserUploadedVideoStatisticsVOToJSON(value?: ResponseListUserUploadedVideoStatisticsVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(UserUploadedVideoStatisticsVOToJSON)),
    };
}

