/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PartitionRecommendTag } from './PartitionRecommendTag';
import {
    PartitionRecommendTagFromJSON,
    PartitionRecommendTagFromJSONTyped,
    PartitionRecommendTagToJSON,
} from './PartitionRecommendTag';

/**
 * 
 * @export
 * @interface ResponseListPartitionRecommendTag
 */
export interface ResponseListPartitionRecommendTag {
    /**
     * 
     * @type {number}
     * @memberof ResponseListPartitionRecommendTag
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseListPartitionRecommendTag
     */
    message?: string;
    /**
     * 
     * @type {Array<PartitionRecommendTag>}
     * @memberof ResponseListPartitionRecommendTag
     */
    data?: Array<PartitionRecommendTag>;
}

/**
 * Check if a given object implements the ResponseListPartitionRecommendTag interface.
 */
export function instanceOfResponseListPartitionRecommendTag(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseListPartitionRecommendTagFromJSON(json: any): ResponseListPartitionRecommendTag {
    return ResponseListPartitionRecommendTagFromJSONTyped(json, false);
}

export function ResponseListPartitionRecommendTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListPartitionRecommendTag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(PartitionRecommendTagFromJSON)),
    };
}

export function ResponseListPartitionRecommendTagToJSON(value?: ResponseListPartitionRecommendTag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(PartitionRecommendTagToJSON)),
    };
}

