/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateVideoPostVo } from './CreateVideoPostVo';
import {
    CreateVideoPostVoFromJSON,
    CreateVideoPostVoFromJSONTyped,
    CreateVideoPostVoToJSON,
} from './CreateVideoPostVo';

/**
 * 
 * @export
 * @interface ResponseCreateVideoPostVo
 */
export interface ResponseCreateVideoPostVo {
    /**
     * 
     * @type {number}
     * @memberof ResponseCreateVideoPostVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseCreateVideoPostVo
     */
    message?: string;
    /**
     * 
     * @type {CreateVideoPostVo}
     * @memberof ResponseCreateVideoPostVo
     */
    data?: CreateVideoPostVo;
}

/**
 * Check if a given object implements the ResponseCreateVideoPostVo interface.
 */
export function instanceOfResponseCreateVideoPostVo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseCreateVideoPostVoFromJSON(json: any): ResponseCreateVideoPostVo {
    return ResponseCreateVideoPostVoFromJSONTyped(json, false);
}

export function ResponseCreateVideoPostVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseCreateVideoPostVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : CreateVideoPostVoFromJSON(json['data']),
    };
}

export function ResponseCreateVideoPostVoToJSON(value?: ResponseCreateVideoPostVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': CreateVideoPostVoToJSON(value.data),
    };
}

