/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VideoPostDetailVO } from './VideoPostDetailVO';
import {
    VideoPostDetailVOFromJSON,
    VideoPostDetailVOFromJSONTyped,
    VideoPostDetailVOToJSON,
} from './VideoPostDetailVO';

/**
 * 
 * @export
 * @interface ResponseVideoPostDetailVO
 */
export interface ResponseVideoPostDetailVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseVideoPostDetailVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseVideoPostDetailVO
     */
    message?: string;
    /**
     * 
     * @type {VideoPostDetailVO}
     * @memberof ResponseVideoPostDetailVO
     */
    data?: VideoPostDetailVO;
}

/**
 * Check if a given object implements the ResponseVideoPostDetailVO interface.
 */
export function instanceOfResponseVideoPostDetailVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseVideoPostDetailVOFromJSON(json: any): ResponseVideoPostDetailVO {
    return ResponseVideoPostDetailVOFromJSONTyped(json, false);
}

export function ResponseVideoPostDetailVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseVideoPostDetailVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : VideoPostDetailVOFromJSON(json['data']),
    };
}

export function ResponseVideoPostDetailVOToJSON(value?: ResponseVideoPostDetailVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': VideoPostDetailVOToJSON(value.data),
    };
}

