/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VideoPostBriefVO } from './VideoPostBriefVO';
import {
    VideoPostBriefVOFromJSON,
    VideoPostBriefVOFromJSONTyped,
    VideoPostBriefVOToJSON,
} from './VideoPostBriefVO';

/**
 * 
 * @export
 * @interface ResponseVideoPostBriefVO
 */
export interface ResponseVideoPostBriefVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseVideoPostBriefVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseVideoPostBriefVO
     */
    message?: string;
    /**
     * 
     * @type {VideoPostBriefVO}
     * @memberof ResponseVideoPostBriefVO
     */
    data?: VideoPostBriefVO;
}

/**
 * Check if a given object implements the ResponseVideoPostBriefVO interface.
 */
export function instanceOfResponseVideoPostBriefVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseVideoPostBriefVOFromJSON(json: any): ResponseVideoPostBriefVO {
    return ResponseVideoPostBriefVOFromJSONTyped(json, false);
}

export function ResponseVideoPostBriefVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseVideoPostBriefVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : VideoPostBriefVOFromJSON(json['data']),
    };
}

export function ResponseVideoPostBriefVOToJSON(value?: ResponseVideoPostBriefVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': VideoPostBriefVOToJSON(value.data),
    };
}

