/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VideoPostBriefVo } from './VideoPostBriefVo';
import {
    VideoPostBriefVoFromJSON,
    VideoPostBriefVoFromJSONTyped,
    VideoPostBriefVoToJSON,
} from './VideoPostBriefVo';

/**
 * 
 * @export
 * @interface ResponseVideoPostBriefVo
 */
export interface ResponseVideoPostBriefVo {
    /**
     * 
     * @type {number}
     * @memberof ResponseVideoPostBriefVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseVideoPostBriefVo
     */
    message?: string;
    /**
     * 
     * @type {VideoPostBriefVo}
     * @memberof ResponseVideoPostBriefVo
     */
    data?: VideoPostBriefVo;
}

/**
 * Check if a given object implements the ResponseVideoPostBriefVo interface.
 */
export function instanceOfResponseVideoPostBriefVo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseVideoPostBriefVoFromJSON(json: any): ResponseVideoPostBriefVo {
    return ResponseVideoPostBriefVoFromJSONTyped(json, false);
}

export function ResponseVideoPostBriefVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseVideoPostBriefVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : VideoPostBriefVoFromJSON(json['data']),
    };
}

export function ResponseVideoPostBriefVoToJSON(value?: ResponseVideoPostBriefVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': VideoPostBriefVoToJSON(value.data),
    };
}

