/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PartitionInfo } from './PartitionInfo';
import {
    PartitionInfoFromJSON,
    PartitionInfoFromJSONTyped,
    PartitionInfoToJSON,
} from './PartitionInfo';

/**
 * 
 * @export
 * @interface ResponseListPartitionInfo
 */
export interface ResponseListPartitionInfo {
    /**
     * 
     * @type {number}
     * @memberof ResponseListPartitionInfo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseListPartitionInfo
     */
    message?: string;
    /**
     * 
     * @type {Array<PartitionInfo>}
     * @memberof ResponseListPartitionInfo
     */
    data?: Array<PartitionInfo>;
}

/**
 * Check if a given object implements the ResponseListPartitionInfo interface.
 */
export function instanceOfResponseListPartitionInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseListPartitionInfoFromJSON(json: any): ResponseListPartitionInfo {
    return ResponseListPartitionInfoFromJSONTyped(json, false);
}

export function ResponseListPartitionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListPartitionInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(PartitionInfoFromJSON)),
    };
}

export function ResponseListPartitionInfoToJSON(value?: ResponseListPartitionInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(PartitionInfoToJSON)),
    };
}

