/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserUploadedVideoStatisticsVO } from './UserUploadedVideoStatisticsVO';
import {
    UserUploadedVideoStatisticsVOFromJSON,
    UserUploadedVideoStatisticsVOFromJSONTyped,
    UserUploadedVideoStatisticsVOToJSON,
} from './UserUploadedVideoStatisticsVO';

/**
 * 
 * @export
 * @interface ResponseUserUploadedVideoStatisticsVO
 */
export interface ResponseUserUploadedVideoStatisticsVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseUserUploadedVideoStatisticsVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseUserUploadedVideoStatisticsVO
     */
    message?: string;
    /**
     * 
     * @type {UserUploadedVideoStatisticsVO}
     * @memberof ResponseUserUploadedVideoStatisticsVO
     */
    data?: UserUploadedVideoStatisticsVO;
}

/**
 * Check if a given object implements the ResponseUserUploadedVideoStatisticsVO interface.
 */
export function instanceOfResponseUserUploadedVideoStatisticsVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseUserUploadedVideoStatisticsVOFromJSON(json: any): ResponseUserUploadedVideoStatisticsVO {
    return ResponseUserUploadedVideoStatisticsVOFromJSONTyped(json, false);
}

export function ResponseUserUploadedVideoStatisticsVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseUserUploadedVideoStatisticsVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : UserUploadedVideoStatisticsVOFromJSON(json['data']),
    };
}

export function ResponseUserUploadedVideoStatisticsVOToJSON(value?: ResponseUserUploadedVideoStatisticsVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': UserUploadedVideoStatisticsVOToJSON(value.data),
    };
}

