/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HomeRecommendVO } from './HomeRecommendVO';
import {
    HomeRecommendVOFromJSON,
    HomeRecommendVOFromJSONTyped,
    HomeRecommendVOToJSON,
} from './HomeRecommendVO';

/**
 * 
 * @export
 * @interface ResponseHomeRecommendVO
 */
export interface ResponseHomeRecommendVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseHomeRecommendVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseHomeRecommendVO
     */
    message?: string;
    /**
     * 
     * @type {HomeRecommendVO}
     * @memberof ResponseHomeRecommendVO
     */
    data?: HomeRecommendVO;
}

/**
 * Check if a given object implements the ResponseHomeRecommendVO interface.
 */
export function instanceOfResponseHomeRecommendVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseHomeRecommendVOFromJSON(json: any): ResponseHomeRecommendVO {
    return ResponseHomeRecommendVOFromJSONTyped(json, false);
}

export function ResponseHomeRecommendVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseHomeRecommendVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : HomeRecommendVOFromJSON(json['data']),
    };
}

export function ResponseHomeRecommendVOToJSON(value?: ResponseHomeRecommendVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': HomeRecommendVOToJSON(value.data),
    };
}

