/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateVideoResourceConversionStateDTO
 */
export interface UpdateVideoResourceConversionStateDTO {
    /**
     * 
     * @type {number}
     * @memberof UpdateVideoResourceConversionStateDTO
     */
    videoId?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateVideoResourceConversionStateDTO
     */
    convertState?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateVideoResourceConversionStateDTO
     */
    convertErrMessage?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateVideoResourceConversionStateDTO
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateVideoResourceConversionStateDTO
     */
    dashMpdUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateVideoResourceConversionStateDTO
     */
    conversionAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateVideoResourceConversionStateDTO
     */
    videoAdaptions?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateVideoResourceConversionStateDTO
     */
    audioAdaptions?: string;
}

/**
 * Check if a given object implements the UpdateVideoResourceConversionStateDTO interface.
 */
export function instanceOfUpdateVideoResourceConversionStateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateVideoResourceConversionStateDTOFromJSON(json: any): UpdateVideoResourceConversionStateDTO {
    return UpdateVideoResourceConversionStateDTOFromJSONTyped(json, false);
}

export function UpdateVideoResourceConversionStateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateVideoResourceConversionStateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'videoId': !exists(json, 'videoId') ? undefined : json['videoId'],
        'convertState': !exists(json, 'convertState') ? undefined : json['convertState'],
        'convertErrMessage': !exists(json, 'convertErrMessage') ? undefined : json['convertErrMessage'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'dashMpdUrl': !exists(json, 'dashMpdUrl') ? undefined : json['dashMpdUrl'],
        'conversionAt': !exists(json, 'conversionAt') ? undefined : (new Date(json['conversionAt'])),
        'videoAdaptions': !exists(json, 'videoAdaptions') ? undefined : json['videoAdaptions'],
        'audioAdaptions': !exists(json, 'audioAdaptions') ? undefined : json['audioAdaptions'],
    };
}

export function UpdateVideoResourceConversionStateDTOToJSON(value?: UpdateVideoResourceConversionStateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'videoId': value.videoId,
        'convertState': value.convertState,
        'convertErrMessage': value.convertErrMessage,
        'duration': value.duration,
        'dashMpdUrl': value.dashMpdUrl,
        'conversionAt': value.conversionAt === undefined ? undefined : (value.conversionAt.toISOString()),
        'videoAdaptions': value.videoAdaptions,
        'audioAdaptions': value.audioAdaptions,
    };
}

