/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePostBriefDTO
 */
export interface UpdatePostBriefDTO {
    /**
     * 
     * @type {number}
     * @memberof UpdatePostBriefDTO
     */
    nkid?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostBriefDTO
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostBriefDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostBriefDTO
     */
    coverUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePostBriefDTO
     */
    videoUrl?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdatePostBriefDTO
     */
    tags?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdatePostBriefDTO
     */
    isPostPublic?: boolean;
}

/**
 * Check if a given object implements the UpdatePostBriefDTO interface.
 */
export function instanceOfUpdatePostBriefDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdatePostBriefDTOFromJSON(json: any): UpdatePostBriefDTO {
    return UpdatePostBriefDTOFromJSONTyped(json, false);
}

export function UpdatePostBriefDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePostBriefDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nkid': !exists(json, 'nkid') ? undefined : json['nkid'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'coverUrl': !exists(json, 'coverUrl') ? undefined : json['coverUrl'],
        'videoUrl': !exists(json, 'videoUrl') ? undefined : json['videoUrl'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'isPostPublic': !exists(json, 'isPostPublic') ? undefined : json['isPostPublic'],
    };
}

export function UpdatePostBriefDTOToJSON(value?: UpdatePostBriefDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nkid': value.nkid,
        'title': value.title,
        'description': value.description,
        'coverUrl': value.coverUrl,
        'videoUrl': value.videoUrl,
        'tags': value.tags,
        'isPostPublic': value.isPostPublic,
    };
}

