/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadUserVo
 */
export interface UploadUserVo {
    /**
     * 
     * @type {string}
     * @memberof UploadUserVo
     */
    username?: string;
    /**
     * 
     * @type {number}
     * @memberof UploadUserVo
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof UploadUserVo
     */
    sign?: string;
    /**
     * 
     * @type {number}
     * @memberof UploadUserVo
     */
    fans?: number;
    /**
     * 
     * @type {string}
     * @memberof UploadUserVo
     */
    avatarUrl?: string;
}

/**
 * Check if a given object implements the UploadUserVo interface.
 */
export function instanceOfUploadUserVo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UploadUserVoFromJSON(json: any): UploadUserVo {
    return UploadUserVoFromJSONTyped(json, false);
}

export function UploadUserVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadUserVo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'sign': !exists(json, 'sign') ? undefined : json['sign'],
        'fans': !exists(json, 'fans') ? undefined : json['fans'],
        'avatarUrl': !exists(json, 'avatarUrl') ? undefined : json['avatarUrl'],
    };
}

export function UploadUserVoToJSON(value?: UploadUserVo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'userId': value.userId,
        'sign': value.sign,
        'fans': value.fans,
        'avatarUrl': value.avatarUrl,
    };
}

