/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadUserVO
 */
export interface UploadUserVO {
    /**
     * 
     * @type {string}
     * @memberof UploadUserVO
     */
    username: string;
    /**
     * 
     * @type {number}
     * @memberof UploadUserVO
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof UploadUserVO
     */
    sign: string;
    /**
     * 
     * @type {number}
     * @memberof UploadUserVO
     */
    fans: number;
    /**
     * 
     * @type {string}
     * @memberof UploadUserVO
     */
    avatarUrl: string;
}

/**
 * Check if a given object implements the UploadUserVO interface.
 */
export function instanceOfUploadUserVO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "sign" in value;
    isInstance = isInstance && "fans" in value;
    isInstance = isInstance && "avatarUrl" in value;

    return isInstance;
}

export function UploadUserVOFromJSON(json: any): UploadUserVO {
    return UploadUserVOFromJSONTyped(json, false);
}

export function UploadUserVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadUserVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'userId': json['userId'],
        'sign': json['sign'],
        'fans': json['fans'],
        'avatarUrl': json['avatarUrl'],
    };
}

export function UploadUserVOToJSON(value?: UploadUserVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'userId': value.userId,
        'sign': value.sign,
        'fans': value.fans,
        'avatarUrl': value.avatarUrl,
    };
}

