/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUploadedVideoPostResourceVO
 */
export interface UserUploadedVideoPostResourceVO {
    /**
     * 
     * @type {number}
     * @memberof UserUploadedVideoPostResourceVO
     */
    videoId?: number;
    /**
     * 
     * @type {number}
     * @memberof UserUploadedVideoPostResourceVO
     */
    duration?: number;
    /**
     * 
     * @type {number}
     * @memberof UserUploadedVideoPostResourceVO
     */
    state?: number;
    /**
     * 
     * @type {string}
     * @memberof UserUploadedVideoPostResourceVO
     */
    reviewFailedReason?: string;
    /**
     * 
     * @type {number}
     * @memberof UserUploadedVideoPostResourceVO
     */
    conversionState?: number;
    /**
     * 
     * @type {string}
     * @memberof UserUploadedVideoPostResourceVO
     */
    conversionFailedReason?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUploadedVideoPostResourceVO
     */
    dashMpdUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserUploadedVideoPostResourceVO
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the UserUploadedVideoPostResourceVO interface.
 */
export function instanceOfUserUploadedVideoPostResourceVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserUploadedVideoPostResourceVOFromJSON(json: any): UserUploadedVideoPostResourceVO {
    return UserUploadedVideoPostResourceVOFromJSONTyped(json, false);
}

export function UserUploadedVideoPostResourceVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUploadedVideoPostResourceVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'videoId': !exists(json, 'videoId') ? undefined : json['videoId'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'reviewFailedReason': !exists(json, 'reviewFailedReason') ? undefined : json['reviewFailedReason'],
        'conversionState': !exists(json, 'conversionState') ? undefined : json['conversionState'],
        'conversionFailedReason': !exists(json, 'conversionFailedReason') ? undefined : json['conversionFailedReason'],
        'dashMpdUrl': !exists(json, 'dashMpdUrl') ? undefined : json['dashMpdUrl'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function UserUploadedVideoPostResourceVOToJSON(value?: UserUploadedVideoPostResourceVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'videoId': value.videoId,
        'duration': value.duration,
        'state': value.state,
        'reviewFailedReason': value.reviewFailedReason,
        'conversionState': value.conversionState,
        'conversionFailedReason': value.conversionFailedReason,
        'dashMpdUrl': value.dashMpdUrl,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

