/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UploadUserVO } from './UploadUserVO';
import {
    UploadUserVOFromJSON,
    UploadUserVOFromJSONTyped,
    UploadUserVOToJSON,
} from './UploadUserVO';

/**
 * 
 * @export
 * @interface VideoPostBriefVO
 */
export interface VideoPostBriefVO {
    /**
     * 
     * @type {number}
     * @memberof VideoPostBriefVO
     */
    nkid: number;
    /**
     * 
     * @type {string}
     * @memberof VideoPostBriefVO
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof VideoPostBriefVO
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof VideoPostBriefVO
     */
    coverUrl: string;
    /**
     * 
     * @type {number}
     * @memberof VideoPostBriefVO
     */
    visit: number;
    /**
     * 
     * @type {UploadUserVO}
     * @memberof VideoPostBriefVO
     */
    uploader: UploadUserVO;
    /**
     * 
     * @type {Array<string>}
     * @memberof VideoPostBriefVO
     */
    tags: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof VideoPostBriefVO
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof VideoPostBriefVO
     */
    partitionName: string;
    /**
     * 
     * @type {number}
     * @memberof VideoPostBriefVO
     */
    partitionId: number;
    /**
     * 
     * @type {Date}
     * @memberof VideoPostBriefVO
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the VideoPostBriefVO interface.
 */
export function instanceOfVideoPostBriefVO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nkid" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "coverUrl" in value;
    isInstance = isInstance && "visit" in value;
    isInstance = isInstance && "uploader" in value;
    isInstance = isInstance && "tags" in value;
    isInstance = isInstance && "duration" in value;
    isInstance = isInstance && "partitionName" in value;
    isInstance = isInstance && "partitionId" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function VideoPostBriefVOFromJSON(json: any): VideoPostBriefVO {
    return VideoPostBriefVOFromJSONTyped(json, false);
}

export function VideoPostBriefVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoPostBriefVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nkid': json['nkid'],
        'title': json['title'],
        'description': json['description'],
        'coverUrl': json['coverUrl'],
        'visit': json['visit'],
        'uploader': UploadUserVOFromJSON(json['uploader']),
        'tags': json['tags'],
        'duration': json['duration'],
        'partitionName': json['partitionName'],
        'partitionId': json['partitionId'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function VideoPostBriefVOToJSON(value?: VideoPostBriefVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nkid': value.nkid,
        'title': value.title,
        'description': value.description,
        'coverUrl': value.coverUrl,
        'visit': value.visit,
        'uploader': UploadUserVOToJSON(value.uploader),
        'tags': value.tags,
        'duration': value.duration,
        'partitionName': value.partitionName,
        'partitionId': value.partitionId,
        'createdAt': (value.createdAt.toISOString()),
    };
}

