/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoPostResourceVO
 */
export interface VideoPostResourceVO {
    /**
     * 
     * @type {number}
     * @memberof VideoPostResourceVO
     */
    videoId: number;
    /**
     * 
     * @type {string}
     * @memberof VideoPostResourceVO
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof VideoPostResourceVO
     */
    visit: number;
    /**
     * 
     * @type {string}
     * @memberof VideoPostResourceVO
     */
    dashMpdUrl: string;
    /**
     * 
     * @type {string}
     * @memberof VideoPostResourceVO
     */
    videoAdaptions: string;
    /**
     * 
     * @type {string}
     * @memberof VideoPostResourceVO
     */
    audioAdaptions: string;
}

/**
 * Check if a given object implements the VideoPostResourceVO interface.
 */
export function instanceOfVideoPostResourceVO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "videoId" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "visit" in value;
    isInstance = isInstance && "dashMpdUrl" in value;
    isInstance = isInstance && "videoAdaptions" in value;
    isInstance = isInstance && "audioAdaptions" in value;

    return isInstance;
}

export function VideoPostResourceVOFromJSON(json: any): VideoPostResourceVO {
    return VideoPostResourceVOFromJSONTyped(json, false);
}

export function VideoPostResourceVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoPostResourceVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'videoId': json['videoId'],
        'title': json['title'],
        'visit': json['visit'],
        'dashMpdUrl': json['dashMpdUrl'],
        'videoAdaptions': json['videoAdaptions'],
        'audioAdaptions': json['audioAdaptions'],
    };
}

export function VideoPostResourceVOToJSON(value?: VideoPostResourceVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'videoId': value.videoId,
        'title': value.title,
        'visit': value.visit,
        'dashMpdUrl': value.dashMpdUrl,
        'videoAdaptions': value.videoAdaptions,
        'audioAdaptions': value.audioAdaptions,
    };
}

