/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoPostVideosVO
 */
export interface VideoPostVideosVO {
    /**
     * 
     * @type {number}
     * @memberof VideoPostVideosVO
     */
    videoId: number;
    /**
     * 
     * @type {string}
     * @memberof VideoPostVideosVO
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof VideoPostVideosVO
     */
    visit: number;
    /**
     * 
     * @type {string}
     * @memberof VideoPostVideosVO
     */
    dashMpdUrl: string;
}

/**
 * Check if a given object implements the VideoPostVideosVO interface.
 */
export function instanceOfVideoPostVideosVO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "videoId" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "visit" in value;
    isInstance = isInstance && "dashMpdUrl" in value;

    return isInstance;
}

export function VideoPostVideosVOFromJSON(json: any): VideoPostVideosVO {
    return VideoPostVideosVOFromJSONTyped(json, false);
}

export function VideoPostVideosVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoPostVideosVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'videoId': json['videoId'],
        'title': json['title'],
        'visit': json['visit'],
        'dashMpdUrl': json['dashMpdUrl'],
    };
}

export function VideoPostVideosVOToJSON(value?: VideoPostVideosVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'videoId': value.videoId,
        'title': value.title,
        'visit': value.visit,
        'dashMpdUrl': value.dashMpdUrl,
    };
}

