/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoPostDTO
 */
export interface VideoPostDTO {
    /**
     * 
     * @type {number}
     * @memberof VideoPostDTO
     */
    nkid?: number;
    /**
     * 
     * @type {number}
     * @memberof VideoPostDTO
     */
    uid?: number;
    /**
     * 
     * @type {string}
     * @memberof VideoPostDTO
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof VideoPostDTO
     */
    visit?: number;
    /**
     * 
     * @type {string}
     * @memberof VideoPostDTO
     */
    coverUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof VideoPostDTO
     */
    duration?: number;
    /**
     * 
     * @type {number}
     * @memberof VideoPostDTO
     */
    shared?: number;
    /**
     * 
     * @type {string}
     * @memberof VideoPostDTO
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof VideoPostDTO
     */
    partitionId?: number;
    /**
     * 
     * @type {string}
     * @memberof VideoPostDTO
     */
    partitionName?: string;
    /**
     * 
     * @type {Date}
     * @memberof VideoPostDTO
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the VideoPostDTO interface.
 */
export function instanceOfVideoPostDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VideoPostDTOFromJSON(json: any): VideoPostDTO {
    return VideoPostDTOFromJSONTyped(json, false);
}

export function VideoPostDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoPostDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nkid': !exists(json, 'nkid') ? undefined : json['nkid'],
        'uid': !exists(json, 'uid') ? undefined : json['uid'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'visit': !exists(json, 'visit') ? undefined : json['visit'],
        'coverUrl': !exists(json, 'coverUrl') ? undefined : json['coverUrl'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'shared': !exists(json, 'shared') ? undefined : json['shared'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'partitionId': !exists(json, 'partitionId') ? undefined : json['partitionId'],
        'partitionName': !exists(json, 'partitionName') ? undefined : json['partitionName'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function VideoPostDTOToJSON(value?: VideoPostDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nkid': value.nkid,
        'uid': value.uid,
        'title': value.title,
        'visit': value.visit,
        'coverUrl': value.coverUrl,
        'duration': value.duration,
        'shared': value.shared,
        'description': value.description,
        'partitionId': value.partitionId,
        'partitionName': value.partitionName,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

