/* tslint:disable */
/* eslint-disable */
/**
 * service-video
 * 视频服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoHelloWorldCardVO
 */
export interface VideoHelloWorldCardVO {
    /**
     * 
     * @type {number}
     * @memberof VideoHelloWorldCardVO
     */
    nkid?: number;
    /**
     * 
     * @type {string}
     * @memberof VideoHelloWorldCardVO
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof VideoHelloWorldCardVO
     */
    coverUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof VideoHelloWorldCardVO
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the VideoHelloWorldCardVO interface.
 */
export function instanceOfVideoHelloWorldCardVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VideoHelloWorldCardVOFromJSON(json: any): VideoHelloWorldCardVO {
    return VideoHelloWorldCardVOFromJSONTyped(json, false);
}

export function VideoHelloWorldCardVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoHelloWorldCardVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nkid': !exists(json, 'nkid') ? undefined : json['nkid'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'coverUrl': !exists(json, 'coverUrl') ? undefined : json['coverUrl'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function VideoHelloWorldCardVOToJSON(value?: VideoHelloWorldCardVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nkid': value.nkid,
        'title': value.title,
        'coverUrl': value.coverUrl,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

