/* tslint:disable */
/* eslint-disable */
/**
 * service-user
 * 用户服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmailLoginDTO,
  EmailPasswordLoginDTO,
  PostVideoCoinDTO,
  ResponseMyUserDetailVO,
  ResponseObject,
  ResponseString,
  ResponseUserDetailVO,
  SendLoginEmailCodeDTO,
  SendResetPasswordEmailCodeDTO,
  UpdatePasswordByEmailCodeDTO,
  UpdatePasswordByOldPasswordDTO,
  UpdateUserDetailDTO,
} from '../models/index';
import {
    EmailLoginDTOFromJSON,
    EmailLoginDTOToJSON,
    EmailPasswordLoginDTOFromJSON,
    EmailPasswordLoginDTOToJSON,
    PostVideoCoinDTOFromJSON,
    PostVideoCoinDTOToJSON,
    ResponseMyUserDetailVOFromJSON,
    ResponseMyUserDetailVOToJSON,
    ResponseObjectFromJSON,
    ResponseObjectToJSON,
    ResponseStringFromJSON,
    ResponseStringToJSON,
    ResponseUserDetailVOFromJSON,
    ResponseUserDetailVOToJSON,
    SendLoginEmailCodeDTOFromJSON,
    SendLoginEmailCodeDTOToJSON,
    SendResetPasswordEmailCodeDTOFromJSON,
    SendResetPasswordEmailCodeDTOToJSON,
    UpdatePasswordByEmailCodeDTOFromJSON,
    UpdatePasswordByEmailCodeDTOToJSON,
    UpdatePasswordByOldPasswordDTOFromJSON,
    UpdatePasswordByOldPasswordDTOToJSON,
    UpdateUserDetailDTOFromJSON,
    UpdateUserDetailDTOToJSON,
} from '../models/index';

export interface GetUserDetailRequest {
    uid: number;
}

export interface LoginRequest {
    emailLoginDTO: EmailLoginDTO;
}

export interface LoginByEmailPasswordRequest {
    emailPasswordLoginDTO: EmailPasswordLoginDTO;
}

export interface PostVideoCoinRequest {
    postVideoCoinDTO: PostVideoCoinDTO;
}

export interface SendLoginEmailCodeRequest {
    sendLoginEmailCodeDTO: SendLoginEmailCodeDTO;
}

export interface SendPasswordResetEmailCodeRequest {
    sendResetPasswordEmailCodeDTO: SendResetPasswordEmailCodeDTO;
}

export interface UpdatePasswordByEmailCodeRequest {
    updatePasswordByEmailCodeDTO: UpdatePasswordByEmailCodeDTO;
}

export interface UpdatePasswordByOldPasswordRequest {
    updatePasswordByOldPasswordDTO: UpdatePasswordByOldPasswordDTO;
}

export interface UpdateUserDetailRequest {
    updateUserDetailDTO: UpdateUserDetailDTO;
}

/**
 * 
 */
export class UserControllerApi extends runtime.BaseAPI {

    /**
     * 获取头像上传链接
     */
    async generateAvatarUploadURLRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseString>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user/generateAvatarUploadURL`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseStringFromJSON(jsonValue));
    }

    /**
     * 获取头像上传链接
     */
    async generateAvatarUploadURL(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseString> {
        const response = await this.generateAvatarUploadURLRaw(initOverrides);
        return await response.value();
    }

    /**
     * 查询用户资料
     */
    async getUserDetailRaw(requestParameters: GetUserDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseUserDetailVO>> {
        if (requestParameters.uid === null || requestParameters.uid === undefined) {
            throw new runtime.RequiredError('uid','Required parameter requestParameters.uid was null or undefined when calling getUserDetail.');
        }

        const queryParameters: any = {};

        if (requestParameters.uid !== undefined) {
            queryParameters['uid'] = requestParameters.uid;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user/getUserDetail`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseUserDetailVOFromJSON(jsonValue));
    }

    /**
     * 查询用户资料
     */
    async getUserDetail(requestParameters: GetUserDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseUserDetailVO> {
        const response = await this.getUserDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 通过邮箱与验证码进行登录
     * 登录
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseObject>> {
        if (requestParameters.emailLoginDTO === null || requestParameters.emailLoginDTO === undefined) {
            throw new runtime.RequiredError('emailLoginDTO','Required parameter requestParameters.emailLoginDTO was null or undefined when calling login.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmailLoginDTOToJSON(requestParameters.emailLoginDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseObjectFromJSON(jsonValue));
    }

    /**
     * 通过邮箱与验证码进行登录
     * 登录
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseObject> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 通过邮箱与密码进行登录
     * 登录
     */
    async loginByEmailPasswordRaw(requestParameters: LoginByEmailPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseObject>> {
        if (requestParameters.emailPasswordLoginDTO === null || requestParameters.emailPasswordLoginDTO === undefined) {
            throw new runtime.RequiredError('emailPasswordLoginDTO','Required parameter requestParameters.emailPasswordLoginDTO was null or undefined when calling loginByEmailPassword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/loginByEmailPassword`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmailPasswordLoginDTOToJSON(requestParameters.emailPasswordLoginDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseObjectFromJSON(jsonValue));
    }

    /**
     * 通过邮箱与密码进行登录
     * 登录
     */
    async loginByEmailPassword(requestParameters: LoginByEmailPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseObject> {
        const response = await this.loginByEmailPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 查询当前用户的个人资料
     */
    async myUserDetailRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseMyUserDetailVO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/user/myUserDetail`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseMyUserDetailVOFromJSON(jsonValue));
    }

    /**
     * 查询当前用户的个人资料
     */
    async myUserDetail(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseMyUserDetailVO> {
        const response = await this.myUserDetailRaw(initOverrides);
        return await response.value();
    }

    /**
     * 视频投币
     */
    async postVideoCoinRaw(requestParameters: PostVideoCoinRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseObject>> {
        if (requestParameters.postVideoCoinDTO === null || requestParameters.postVideoCoinDTO === undefined) {
            throw new runtime.RequiredError('postVideoCoinDTO','Required parameter requestParameters.postVideoCoinDTO was null or undefined when calling postVideoCoin.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/postVideoCoin`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostVideoCoinDTOToJSON(requestParameters.postVideoCoinDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseObjectFromJSON(jsonValue));
    }

    /**
     * 视频投币
     */
    async postVideoCoin(requestParameters: PostVideoCoinRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseObject> {
        const response = await this.postVideoCoinRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 发送登录邮件，若当前邮箱未注册，则发送注册邮件
     * 发送登录邮件
     */
    async sendLoginEmailCodeRaw(requestParameters: SendLoginEmailCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseObject>> {
        if (requestParameters.sendLoginEmailCodeDTO === null || requestParameters.sendLoginEmailCodeDTO === undefined) {
            throw new runtime.RequiredError('sendLoginEmailCodeDTO','Required parameter requestParameters.sendLoginEmailCodeDTO was null or undefined when calling sendLoginEmailCode.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/sendLoginEmailCode`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendLoginEmailCodeDTOToJSON(requestParameters.sendLoginEmailCodeDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseObjectFromJSON(jsonValue));
    }

    /**
     * 发送登录邮件，若当前邮箱未注册，则发送注册邮件
     * 发送登录邮件
     */
    async sendLoginEmailCode(requestParameters: SendLoginEmailCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseObject> {
        const response = await this.sendLoginEmailCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 发送密码重置邮件
     */
    async sendPasswordResetEmailCodeRaw(requestParameters: SendPasswordResetEmailCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseObject>> {
        if (requestParameters.sendResetPasswordEmailCodeDTO === null || requestParameters.sendResetPasswordEmailCodeDTO === undefined) {
            throw new runtime.RequiredError('sendResetPasswordEmailCodeDTO','Required parameter requestParameters.sendResetPasswordEmailCodeDTO was null or undefined when calling sendPasswordResetEmailCode.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/sendPasswordResetEmailCode`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendResetPasswordEmailCodeDTOToJSON(requestParameters.sendResetPasswordEmailCodeDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseObjectFromJSON(jsonValue));
    }

    /**
     * 发送密码重置邮件
     */
    async sendPasswordResetEmailCode(requestParameters: SendPasswordResetEmailCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseObject> {
        const response = await this.sendPasswordResetEmailCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 通过邮箱与邮箱验证码进行密码更新
     * 更新密码
     */
    async updatePasswordByEmailCodeRaw(requestParameters: UpdatePasswordByEmailCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseObject>> {
        if (requestParameters.updatePasswordByEmailCodeDTO === null || requestParameters.updatePasswordByEmailCodeDTO === undefined) {
            throw new runtime.RequiredError('updatePasswordByEmailCodeDTO','Required parameter requestParameters.updatePasswordByEmailCodeDTO was null or undefined when calling updatePasswordByEmailCode.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/updatePasswordByEmailCode`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePasswordByEmailCodeDTOToJSON(requestParameters.updatePasswordByEmailCodeDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseObjectFromJSON(jsonValue));
    }

    /**
     * 通过邮箱与邮箱验证码进行密码更新
     * 更新密码
     */
    async updatePasswordByEmailCode(requestParameters: UpdatePasswordByEmailCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseObject> {
        const response = await this.updatePasswordByEmailCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 通过旧密码进行密码更新
     * 更新密码
     */
    async updatePasswordByOldPasswordRaw(requestParameters: UpdatePasswordByOldPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseObject>> {
        if (requestParameters.updatePasswordByOldPasswordDTO === null || requestParameters.updatePasswordByOldPasswordDTO === undefined) {
            throw new runtime.RequiredError('updatePasswordByOldPasswordDTO','Required parameter requestParameters.updatePasswordByOldPasswordDTO was null or undefined when calling updatePasswordByOldPassword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/updatePasswordByOldPassword`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePasswordByOldPasswordDTOToJSON(requestParameters.updatePasswordByOldPasswordDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseObjectFromJSON(jsonValue));
    }

    /**
     * 通过旧密码进行密码更新
     * 更新密码
     */
    async updatePasswordByOldPassword(requestParameters: UpdatePasswordByOldPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseObject> {
        const response = await this.updatePasswordByOldPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新用户资料
     */
    async updateUserDetailRaw(requestParameters: UpdateUserDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseObject>> {
        if (requestParameters.updateUserDetailDTO === null || requestParameters.updateUserDetailDTO === undefined) {
            throw new runtime.RequiredError('updateUserDetailDTO','Required parameter requestParameters.updateUserDetailDTO was null or undefined when calling updateUserDetail.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/user/updateUserDetail`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserDetailDTOToJSON(requestParameters.updateUserDetailDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseObjectFromJSON(jsonValue));
    }

    /**
     * 更新用户资料
     */
    async updateUserDetail(requestParameters: UpdateUserDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseObject> {
        const response = await this.updateUserDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
