/* tslint:disable */
/* eslint-disable */
/**
 * service-comment
 * 评论服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommentVO } from './CommentVO';
import {
    CommentVOFromJSON,
    CommentVOFromJSONTyped,
    CommentVOToJSON,
} from './CommentVO';

/**
 * 
 * @export
 * @interface CommentPageVO
 */
export interface CommentPageVO {
    /**
     * 
     * @type {number}
     * @memberof CommentPageVO
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof CommentPageVO
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CommentPageVO
     */
    size: number;
    /**
     * 
     * @type {Array<CommentVO>}
     * @memberof CommentPageVO
     */
    comments: Array<CommentVO>;
}

/**
 * Check if a given object implements the CommentPageVO interface.
 */
export function instanceOfCommentPageVO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "size" in value;
    isInstance = isInstance && "comments" in value;

    return isInstance;
}

export function CommentPageVOFromJSON(json: any): CommentPageVO {
    return CommentPageVOFromJSONTyped(json, false);
}

export function CommentPageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentPageVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'size': json['size'],
        'comments': ((json['comments'] as Array<any>).map(CommentVOFromJSON)),
    };
}

export function CommentPageVOToJSON(value?: CommentPageVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'page': value.page,
        'size': value.size,
        'comments': ((value.comments as Array<any>).map(CommentVOToJSON)),
    };
}

