/* tslint:disable */
/* eslint-disable */
/**
 * service-comment
 * 评论服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentUserVO
 */
export interface CommentUserVO {
    /**
     * 
     * @type {number}
     * @memberof CommentUserVO
     */
    uid?: number;
    /**
     * 
     * @type {string}
     * @memberof CommentUserVO
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentUserVO
     */
    avatarUrl?: string;
}

/**
 * Check if a given object implements the CommentUserVO interface.
 */
export function instanceOfCommentUserVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CommentUserVOFromJSON(json: any): CommentUserVO {
    return CommentUserVOFromJSONTyped(json, false);
}

export function CommentUserVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentUserVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uid': !exists(json, 'uid') ? undefined : json['uid'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'avatarUrl': !exists(json, 'avatarUrl') ? undefined : json['avatarUrl'],
    };
}

export function CommentUserVOToJSON(value?: CommentUserVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uid': value.uid,
        'username': value.username,
        'avatarUrl': value.avatarUrl,
    };
}

