/* tslint:disable */
/* eslint-disable */
/**
 * service-comment
 * 评论服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommentUserVO } from './CommentUserVO';
import {
    CommentUserVOFromJSON,
    CommentUserVOFromJSONTyped,
    CommentUserVOToJSON,
} from './CommentUserVO';
import type { SecondaryCommentPageVO } from './SecondaryCommentPageVO';
import {
    SecondaryCommentPageVOFromJSON,
    SecondaryCommentPageVOFromJSONTyped,
    SecondaryCommentPageVOToJSON,
} from './SecondaryCommentPageVO';

/**
 * 
 * @export
 * @interface CommentVO
 */
export interface CommentVO {
    /**
     * 
     * @type {number}
     * @memberof CommentVO
     */
    commentId: number;
    /**
     * 
     * @type {CommentUserVO}
     * @memberof CommentVO
     */
    commentUserVO: CommentUserVO;
    /**
     * 
     * @type {number}
     * @memberof CommentVO
     */
    oid: number;
    /**
     * 
     * @type {string}
     * @memberof CommentVO
     */
    oidType: CommentVOOidTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CommentVO
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof CommentVO
     */
    likesCount: number;
    /**
     * 
     * @type {SecondaryCommentPageVO}
     * @memberof CommentVO
     */
    initialSecondaryCommentPageVO: SecondaryCommentPageVO;
    /**
     * 
     * @type {Date}
     * @memberof CommentVO
     */
    createdAt: Date;
}


/**
 * @export
 */
export const CommentVOOidTypeEnum = {
    Video: 'VIDEO',
    Activity: 'ACTIVITY'
} as const;
export type CommentVOOidTypeEnum = typeof CommentVOOidTypeEnum[keyof typeof CommentVOOidTypeEnum];


/**
 * Check if a given object implements the CommentVO interface.
 */
export function instanceOfCommentVO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "commentId" in value;
    isInstance = isInstance && "commentUserVO" in value;
    isInstance = isInstance && "oid" in value;
    isInstance = isInstance && "oidType" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "likesCount" in value;
    isInstance = isInstance && "initialSecondaryCommentPageVO" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function CommentVOFromJSON(json: any): CommentVO {
    return CommentVOFromJSONTyped(json, false);
}

export function CommentVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'commentId': json['commentId'],
        'commentUserVO': CommentUserVOFromJSON(json['commentUserVO']),
        'oid': json['oid'],
        'oidType': json['oidType'],
        'content': json['content'],
        'likesCount': json['likesCount'],
        'initialSecondaryCommentPageVO': SecondaryCommentPageVOFromJSON(json['initialSecondaryCommentPageVO']),
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function CommentVOToJSON(value?: CommentVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'commentId': value.commentId,
        'commentUserVO': CommentUserVOToJSON(value.commentUserVO),
        'oid': value.oid,
        'oidType': value.oidType,
        'content': value.content,
        'likesCount': value.likesCount,
        'initialSecondaryCommentPageVO': SecondaryCommentPageVOToJSON(value.initialSecondaryCommentPageVO),
        'createdAt': (value.createdAt.toISOString()),
    };
}

