/* tslint:disable */
/* eslint-disable */
/**
 * service-comment
 * 评论服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommentDTO
 */
export interface CreateCommentDTO {
    /**
     * 对象ID，视频ID或动态ID
     * @type {number}
     * @memberof CreateCommentDTO
     */
    oid: number;
    /**
     * 评论类型，0 视频评论，1 动态评论
     * @type {string}
     * @memberof CreateCommentDTO
     */
    type: CreateCommentDTOTypeEnum;
    /**
     * 评论内容，最大65535字符
     * @type {string}
     * @memberof CreateCommentDTO
     */
    content: string;
    /**
     * 被回复的根评论ID
     * @type {number}
     * @memberof CreateCommentDTO
     */
    replyCid?: number;
    /**
     * 被回复的二级评论ID
     * @type {number}
     * @memberof CreateCommentDTO
     */
    replySecondaryCid?: number;
}


/**
 * @export
 */
export const CreateCommentDTOTypeEnum = {
    Video: 'VIDEO',
    Activity: 'ACTIVITY'
} as const;
export type CreateCommentDTOTypeEnum = typeof CreateCommentDTOTypeEnum[keyof typeof CreateCommentDTOTypeEnum];


/**
 * Check if a given object implements the CreateCommentDTO interface.
 */
export function instanceOfCreateCommentDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "oid" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function CreateCommentDTOFromJSON(json: any): CreateCommentDTO {
    return CreateCommentDTOFromJSONTyped(json, false);
}

export function CreateCommentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'oid': json['oid'],
        'type': json['type'],
        'content': json['content'],
        'replyCid': !exists(json, 'replyCid') ? undefined : json['replyCid'],
        'replySecondaryCid': !exists(json, 'replySecondaryCid') ? undefined : json['replySecondaryCid'],
    };
}

export function CreateCommentDTOToJSON(value?: CreateCommentDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'oid': value.oid,
        'type': value.type,
        'content': value.content,
        'replyCid': value.replyCid,
        'replySecondaryCid': value.replySecondaryCid,
    };
}

