/* tslint:disable */
/* eslint-disable */
/**
 * service-comment
 * 评论服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommentVO } from './CommentVO';
import {
    CommentVOFromJSON,
    CommentVOFromJSONTyped,
    CommentVOToJSON,
} from './CommentVO';

/**
 * 
 * @export
 * @interface ResponseCommentVO
 */
export interface ResponseCommentVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseCommentVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseCommentVO
     */
    message?: string;
    /**
     * 
     * @type {CommentVO}
     * @memberof ResponseCommentVO
     */
    data?: CommentVO;
}

/**
 * Check if a given object implements the ResponseCommentVO interface.
 */
export function instanceOfResponseCommentVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseCommentVOFromJSON(json: any): ResponseCommentVO {
    return ResponseCommentVOFromJSONTyped(json, false);
}

export function ResponseCommentVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseCommentVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : CommentVOFromJSON(json['data']),
    };
}

export function ResponseCommentVOToJSON(value?: ResponseCommentVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': CommentVOToJSON(value.data),
    };
}

