/* tslint:disable */
/* eslint-disable */
/**
 * service-comment
 * 评论服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommentPageVO } from './CommentPageVO';
import {
    CommentPageVOFromJSON,
    CommentPageVOFromJSONTyped,
    CommentPageVOToJSON,
} from './CommentPageVO';

/**
 * 
 * @export
 * @interface ResponseCommentPageVO
 */
export interface ResponseCommentPageVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseCommentPageVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseCommentPageVO
     */
    message?: string;
    /**
     * 
     * @type {CommentPageVO}
     * @memberof ResponseCommentPageVO
     */
    data?: CommentPageVO;
}

/**
 * Check if a given object implements the ResponseCommentPageVO interface.
 */
export function instanceOfResponseCommentPageVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseCommentPageVOFromJSON(json: any): ResponseCommentPageVO {
    return ResponseCommentPageVOFromJSONTyped(json, false);
}

export function ResponseCommentPageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseCommentPageVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : CommentPageVOFromJSON(json['data']),
    };
}

export function ResponseCommentPageVOToJSON(value?: ResponseCommentPageVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': CommentPageVOToJSON(value.data),
    };
}

