/* tslint:disable */
/* eslint-disable */
/**
 * service-comment
 * 评论服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SecondaryCommentPageVO } from './SecondaryCommentPageVO';
import {
    SecondaryCommentPageVOFromJSON,
    SecondaryCommentPageVOFromJSONTyped,
    SecondaryCommentPageVOToJSON,
} from './SecondaryCommentPageVO';

/**
 * 
 * @export
 * @interface ResponseSecondaryCommentPageVO
 */
export interface ResponseSecondaryCommentPageVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseSecondaryCommentPageVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseSecondaryCommentPageVO
     */
    message?: string;
    /**
     * 
     * @type {SecondaryCommentPageVO}
     * @memberof ResponseSecondaryCommentPageVO
     */
    data?: SecondaryCommentPageVO;
}

/**
 * Check if a given object implements the ResponseSecondaryCommentPageVO interface.
 */
export function instanceOfResponseSecondaryCommentPageVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseSecondaryCommentPageVOFromJSON(json: any): ResponseSecondaryCommentPageVO {
    return ResponseSecondaryCommentPageVOFromJSONTyped(json, false);
}

export function ResponseSecondaryCommentPageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseSecondaryCommentPageVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : SecondaryCommentPageVOFromJSON(json['data']),
    };
}

export function ResponseSecondaryCommentPageVOToJSON(value?: ResponseSecondaryCommentPageVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': SecondaryCommentPageVOToJSON(value.data),
    };
}

