/* tslint:disable */
/* eslint-disable */
/**
 * service-comment
 * 评论服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SecondaryCommentVO } from './SecondaryCommentVO';
import {
    SecondaryCommentVOFromJSON,
    SecondaryCommentVOFromJSONTyped,
    SecondaryCommentVOToJSON,
} from './SecondaryCommentVO';

/**
 * 
 * @export
 * @interface SecondaryCommentPageVO
 */
export interface SecondaryCommentPageVO {
    /**
     * 
     * @type {number}
     * @memberof SecondaryCommentPageVO
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof SecondaryCommentPageVO
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof SecondaryCommentPageVO
     */
    size: number;
    /**
     * 
     * @type {Array<SecondaryCommentVO>}
     * @memberof SecondaryCommentPageVO
     */
    secondaryComments: Array<SecondaryCommentVO>;
}

/**
 * Check if a given object implements the SecondaryCommentPageVO interface.
 */
export function instanceOfSecondaryCommentPageVO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "total" in value;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "size" in value;
    isInstance = isInstance && "secondaryComments" in value;

    return isInstance;
}

export function SecondaryCommentPageVOFromJSON(json: any): SecondaryCommentPageVO {
    return SecondaryCommentPageVOFromJSONTyped(json, false);
}

export function SecondaryCommentPageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecondaryCommentPageVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'size': json['size'],
        'secondaryComments': ((json['secondaryComments'] as Array<any>).map(SecondaryCommentVOFromJSON)),
    };
}

export function SecondaryCommentPageVOToJSON(value?: SecondaryCommentPageVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'page': value.page,
        'size': value.size,
        'secondaryComments': ((value.secondaryComments as Array<any>).map(SecondaryCommentVOToJSON)),
    };
}

