/* tslint:disable */
/* eslint-disable */
/**
 * service-comment
 * 评论服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommentUserVO } from './CommentUserVO';
import {
    CommentUserVOFromJSON,
    CommentUserVOFromJSONTyped,
    CommentUserVOToJSON,
} from './CommentUserVO';

/**
 * 
 * @export
 * @interface SecondaryCommentVO
 */
export interface SecondaryCommentVO {
    /**
     * 
     * @type {number}
     * @memberof SecondaryCommentVO
     */
    commentId: number;
    /**
     * 
     * @type {CommentUserVO}
     * @memberof SecondaryCommentVO
     */
    commentUserVO: CommentUserVO;
    /**
     * 
     * @type {number}
     * @memberof SecondaryCommentVO
     */
    oid: number;
    /**
     * 
     * @type {string}
     * @memberof SecondaryCommentVO
     */
    oidType: SecondaryCommentVOOidTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SecondaryCommentVO
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof SecondaryCommentVO
     */
    likesCount: number;
    /**
     * 
     * @type {number}
     * @memberof SecondaryCommentVO
     */
    replyCid: number;
    /**
     * 
     * @type {number}
     * @memberof SecondaryCommentVO
     */
    replySecondaryCid: number;
    /**
     * 
     * @type {Date}
     * @memberof SecondaryCommentVO
     */
    createdAt: Date;
}


/**
 * @export
 */
export const SecondaryCommentVOOidTypeEnum = {
    Video: 'VIDEO',
    Activity: 'ACTIVITY'
} as const;
export type SecondaryCommentVOOidTypeEnum = typeof SecondaryCommentVOOidTypeEnum[keyof typeof SecondaryCommentVOOidTypeEnum];


/**
 * Check if a given object implements the SecondaryCommentVO interface.
 */
export function instanceOfSecondaryCommentVO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "commentId" in value;
    isInstance = isInstance && "commentUserVO" in value;
    isInstance = isInstance && "oid" in value;
    isInstance = isInstance && "oidType" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "likesCount" in value;
    isInstance = isInstance && "replyCid" in value;
    isInstance = isInstance && "replySecondaryCid" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function SecondaryCommentVOFromJSON(json: any): SecondaryCommentVO {
    return SecondaryCommentVOFromJSONTyped(json, false);
}

export function SecondaryCommentVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecondaryCommentVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'commentId': json['commentId'],
        'commentUserVO': CommentUserVOFromJSON(json['commentUserVO']),
        'oid': json['oid'],
        'oidType': json['oidType'],
        'content': json['content'],
        'likesCount': json['likesCount'],
        'replyCid': json['replyCid'],
        'replySecondaryCid': json['replySecondaryCid'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function SecondaryCommentVOToJSON(value?: SecondaryCommentVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'commentId': value.commentId,
        'commentUserVO': CommentUserVOToJSON(value.commentUserVO),
        'oid': value.oid,
        'oidType': value.oidType,
        'content': value.content,
        'likesCount': value.likesCount,
        'replyCid': value.replyCid,
        'replySecondaryCid': value.replySecondaryCid,
        'createdAt': (value.createdAt.toISOString()),
    };
}

