/* tslint:disable */
/* eslint-disable */
/**
 * service-user
 * 用户服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailPasswordLoginDTO
 */
export interface EmailPasswordLoginDTO {
    /**
     * 
     * @type {string}
     * @memberof EmailPasswordLoginDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailPasswordLoginDTO
     */
    password?: string;
}

/**
 * Check if a given object implements the EmailPasswordLoginDTO interface.
 */
export function instanceOfEmailPasswordLoginDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmailPasswordLoginDTOFromJSON(json: any): EmailPasswordLoginDTO {
    return EmailPasswordLoginDTOFromJSONTyped(json, false);
}

export function EmailPasswordLoginDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailPasswordLoginDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function EmailPasswordLoginDTOToJSON(value?: EmailPasswordLoginDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

