/* tslint:disable */
/* eslint-disable */
/**
 * service-user
 * 用户服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailLoginDTO
 */
export interface EmailLoginDTO {
    /**
     * 
     * @type {string}
     * @memberof EmailLoginDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailLoginDTO
     */
    code?: string;
}

/**
 * Check if a given object implements the EmailLoginDTO interface.
 */
export function instanceOfEmailLoginDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EmailLoginDTOFromJSON(json: any): EmailLoginDTO {
    return EmailLoginDTOFromJSONTyped(json, false);
}

export function EmailLoginDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailLoginDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function EmailLoginDTOToJSON(value?: EmailLoginDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'code': value.code,
    };
}

