/* tslint:disable */
/* eslint-disable */
/**
 * service-user
 * 用户服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostVideoCoinDTO
 */
export interface PostVideoCoinDTO {
    /**
     * 视频id
     * @type {number}
     * @memberof PostVideoCoinDTO
     */
    nkid: number;
    /**
     * 硬币数量
     * @type {number}
     * @memberof PostVideoCoinDTO
     */
    coinNum: number;
}

/**
 * Check if a given object implements the PostVideoCoinDTO interface.
 */
export function instanceOfPostVideoCoinDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nkid" in value;
    isInstance = isInstance && "coinNum" in value;

    return isInstance;
}

export function PostVideoCoinDTOFromJSON(json: any): PostVideoCoinDTO {
    return PostVideoCoinDTOFromJSONTyped(json, false);
}

export function PostVideoCoinDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostVideoCoinDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nkid': json['nkid'],
        'coinNum': json['coinNum'],
    };
}

export function PostVideoCoinDTOToJSON(value?: PostVideoCoinDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nkid': value.nkid,
        'coinNum': value.coinNum,
    };
}

