/* tslint:disable */
/* eslint-disable */
/**
 * service-user
 * 用户服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DailyBonusVO } from './DailyBonusVO';
import {
    DailyBonusVOFromJSON,
    DailyBonusVOFromJSONTyped,
    DailyBonusVOToJSON,
} from './DailyBonusVO';

/**
 * 
 * @export
 * @interface ResponseDailyBonusVO
 */
export interface ResponseDailyBonusVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseDailyBonusVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseDailyBonusVO
     */
    message?: string;
    /**
     * 
     * @type {DailyBonusVO}
     * @memberof ResponseDailyBonusVO
     */
    data?: DailyBonusVO;
}

/**
 * Check if a given object implements the ResponseDailyBonusVO interface.
 */
export function instanceOfResponseDailyBonusVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseDailyBonusVOFromJSON(json: any): ResponseDailyBonusVO {
    return ResponseDailyBonusVOFromJSONTyped(json, false);
}

export function ResponseDailyBonusVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseDailyBonusVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : DailyBonusVOFromJSON(json['data']),
    };
}

export function ResponseDailyBonusVOToJSON(value?: ResponseDailyBonusVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': DailyBonusVOToJSON(value.data),
    };
}

