/* tslint:disable */
/* eslint-disable */
/**
 * service-user
 * 用户服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserDetailVO } from './UserDetailVO';
import {
    UserDetailVOFromJSON,
    UserDetailVOFromJSONTyped,
    UserDetailVOToJSON,
} from './UserDetailVO';

/**
 * 
 * @export
 * @interface ResponseUserDetailVO
 */
export interface ResponseUserDetailVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseUserDetailVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseUserDetailVO
     */
    message?: string;
    /**
     * 
     * @type {UserDetailVO}
     * @memberof ResponseUserDetailVO
     */
    data?: UserDetailVO;
}

/**
 * Check if a given object implements the ResponseUserDetailVO interface.
 */
export function instanceOfResponseUserDetailVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseUserDetailVOFromJSON(json: any): ResponseUserDetailVO {
    return ResponseUserDetailVOFromJSONTyped(json, false);
}

export function ResponseUserDetailVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseUserDetailVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : UserDetailVOFromJSON(json['data']),
    };
}

export function ResponseUserDetailVOToJSON(value?: ResponseUserDetailVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': UserDetailVOToJSON(value.data),
    };
}

