/* tslint:disable */
/* eslint-disable */
/**
 * service-user
 * 用户服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendResetPasswordEmailCodeDTO
 */
export interface SendResetPasswordEmailCodeDTO {
    /**
     * 
     * @type {string}
     * @memberof SendResetPasswordEmailCodeDTO
     */
    email?: string;
}

/**
 * Check if a given object implements the SendResetPasswordEmailCodeDTO interface.
 */
export function instanceOfSendResetPasswordEmailCodeDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SendResetPasswordEmailCodeDTOFromJSON(json: any): SendResetPasswordEmailCodeDTO {
    return SendResetPasswordEmailCodeDTOFromJSONTyped(json, false);
}

export function SendResetPasswordEmailCodeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendResetPasswordEmailCodeDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function SendResetPasswordEmailCodeDTOToJSON(value?: SendResetPasswordEmailCodeDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

