/* tslint:disable */
/* eslint-disable */
/**
 * service-user
 * 用户服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePasswordByEmailCodeDTO
 */
export interface UpdatePasswordByEmailCodeDTO {
    /**
     * 
     * @type {string}
     * @memberof UpdatePasswordByEmailCodeDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePasswordByEmailCodeDTO
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePasswordByEmailCodeDTO
     */
    newPassword?: string;
}

/**
 * Check if a given object implements the UpdatePasswordByEmailCodeDTO interface.
 */
export function instanceOfUpdatePasswordByEmailCodeDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdatePasswordByEmailCodeDTOFromJSON(json: any): UpdatePasswordByEmailCodeDTO {
    return UpdatePasswordByEmailCodeDTOFromJSONTyped(json, false);
}

export function UpdatePasswordByEmailCodeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePasswordByEmailCodeDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'newPassword': !exists(json, 'newPassword') ? undefined : json['newPassword'],
    };
}

export function UpdatePasswordByEmailCodeDTOToJSON(value?: UpdatePasswordByEmailCodeDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'code': value.code,
        'newPassword': value.newPassword,
    };
}

