/* tslint:disable */
/* eslint-disable */
/**
 * service-user
 * 用户服务API接口说明
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePasswordByOldPasswordDTO
 */
export interface UpdatePasswordByOldPasswordDTO {
    /**
     * 
     * @type {string}
     * @memberof UpdatePasswordByOldPasswordDTO
     */
    oldPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePasswordByOldPasswordDTO
     */
    newPassword?: string;
}

/**
 * Check if a given object implements the UpdatePasswordByOldPasswordDTO interface.
 */
export function instanceOfUpdatePasswordByOldPasswordDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdatePasswordByOldPasswordDTOFromJSON(json: any): UpdatePasswordByOldPasswordDTO {
    return UpdatePasswordByOldPasswordDTOFromJSONTyped(json, false);
}

export function UpdatePasswordByOldPasswordDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePasswordByOldPasswordDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'oldPassword': !exists(json, 'oldPassword') ? undefined : json['oldPassword'],
        'newPassword': !exists(json, 'newPassword') ? undefined : json['newPassword'],
    };
}

export function UpdatePasswordByOldPasswordDTOToJSON(value?: UpdatePasswordByOldPasswordDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'oldPassword': value.oldPassword,
        'newPassword': value.newPassword,
    };
}

