/* tslint:disable */
/* eslint-disable */
/**
 * service-collection
 * 收藏服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionGroupVO
 */
export interface CollectionGroupVO {
    /**
     * 分组ID
     * @type {number}
     * @memberof CollectionGroupVO
     */
    groupId: number;
    /**
     * 用户ID
     * @type {number}
     * @memberof CollectionGroupVO
     */
    uid: number;
    /**
     * 分组名称
     * @type {string}
     * @memberof CollectionGroupVO
     */
    name: string;
    /**
     * 分组描述
     * @type {string}
     * @memberof CollectionGroupVO
     */
    description: string;
    /**
     * 状态
     * @type {number}
     * @memberof CollectionGroupVO
     */
    state: number;
    /**
     * 预览封面URL，如果无有效视频，为空串
     * @type {string}
     * @memberof CollectionGroupVO
     */
    previewCoverUrl: string;
    /**
     * 收藏数量
     * @type {number}
     * @memberof CollectionGroupVO
     */
    collectionCount: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof CollectionGroupVO
     */
    createdAt: string;
}

/**
 * Check if a given object implements the CollectionGroupVO interface.
 */
export function instanceOfCollectionGroupVO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "groupId" in value;
    isInstance = isInstance && "uid" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "previewCoverUrl" in value;
    isInstance = isInstance && "collectionCount" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function CollectionGroupVOFromJSON(json: any): CollectionGroupVO {
    return CollectionGroupVOFromJSONTyped(json, false);
}

export function CollectionGroupVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionGroupVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'uid': json['uid'],
        'name': json['name'],
        'description': json['description'],
        'state': json['state'],
        'previewCoverUrl': json['previewCoverUrl'],
        'collectionCount': json['collectionCount'],
        'createdAt': json['createdAt'],
    };
}

export function CollectionGroupVOToJSON(value?: CollectionGroupVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groupId': value.groupId,
        'uid': value.uid,
        'name': value.name,
        'description': value.description,
        'state': value.state,
        'previewCoverUrl': value.previewCoverUrl,
        'collectionCount': value.collectionCount,
        'createdAt': value.createdAt,
    };
}

