/* tslint:disable */
/* eslint-disable */
/**
 * service-collection
 * 收藏服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionVideoPostVO
 */
export interface CollectionVideoPostVO {
    /**
     * 
     * @type {number}
     * @memberof CollectionVideoPostVO
     */
    nkid: number;
    /**
     * 
     * @type {string}
     * @memberof CollectionVideoPostVO
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionVideoPostVO
     */
    coverUrl: string;
    /**
     * 
     * @type {number}
     * @memberof CollectionVideoPostVO
     */
    duration: number;
    /**
     * 
     * @type {number}
     * @memberof CollectionVideoPostVO
     */
    visit: number;
    /**
     * 
     * @type {number}
     * @memberof CollectionVideoPostVO
     */
    danmakuNums: number;
    /**
     * 
     * @type {string}
     * @memberof CollectionVideoPostVO
     */
    uploaderName: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionVideoPostVO
     */
    createdAt: string;
}

/**
 * Check if a given object implements the CollectionVideoPostVO interface.
 */
export function instanceOfCollectionVideoPostVO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nkid" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "coverUrl" in value;
    isInstance = isInstance && "duration" in value;
    isInstance = isInstance && "visit" in value;
    isInstance = isInstance && "danmakuNums" in value;
    isInstance = isInstance && "uploaderName" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function CollectionVideoPostVOFromJSON(json: any): CollectionVideoPostVO {
    return CollectionVideoPostVOFromJSONTyped(json, false);
}

export function CollectionVideoPostVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionVideoPostVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nkid': json['nkid'],
        'title': json['title'],
        'coverUrl': json['coverUrl'],
        'duration': json['duration'],
        'visit': json['visit'],
        'danmakuNums': json['danmakuNums'],
        'uploaderName': json['uploaderName'],
        'createdAt': json['createdAt'],
    };
}

export function CollectionVideoPostVOToJSON(value?: CollectionVideoPostVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nkid': value.nkid,
        'title': value.title,
        'coverUrl': value.coverUrl,
        'duration': value.duration,
        'visit': value.visit,
        'danmakuNums': value.danmakuNums,
        'uploaderName': value.uploaderName,
        'createdAt': value.createdAt,
    };
}

