/* tslint:disable */
/* eslint-disable */
/**
 * service-collection
 * 收藏服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CollectionGroupVO } from './CollectionGroupVO';
import {
    CollectionGroupVOFromJSON,
    CollectionGroupVOFromJSONTyped,
    CollectionGroupVOToJSON,
} from './CollectionGroupVO';

/**
 * 
 * @export
 * @interface ResponseCollectionGroupVO
 */
export interface ResponseCollectionGroupVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseCollectionGroupVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseCollectionGroupVO
     */
    message?: string;
    /**
     * 
     * @type {CollectionGroupVO}
     * @memberof ResponseCollectionGroupVO
     */
    data?: CollectionGroupVO;
}

/**
 * Check if a given object implements the ResponseCollectionGroupVO interface.
 */
export function instanceOfResponseCollectionGroupVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseCollectionGroupVOFromJSON(json: any): ResponseCollectionGroupVO {
    return ResponseCollectionGroupVOFromJSONTyped(json, false);
}

export function ResponseCollectionGroupVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseCollectionGroupVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : CollectionGroupVOFromJSON(json['data']),
    };
}

export function ResponseCollectionGroupVOToJSON(value?: ResponseCollectionGroupVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': CollectionGroupVOToJSON(value.data),
    };
}

