/* tslint:disable */
/* eslint-disable */
/**
 * service-collection
 * 收藏服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CollectionVideoPostVO } from './CollectionVideoPostVO';
import {
    CollectionVideoPostVOFromJSON,
    CollectionVideoPostVOFromJSONTyped,
    CollectionVideoPostVOToJSON,
} from './CollectionVideoPostVO';

/**
 * 
 * @export
 * @interface ResponseListCollectionVideoPostVO
 */
export interface ResponseListCollectionVideoPostVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseListCollectionVideoPostVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseListCollectionVideoPostVO
     */
    message?: string;
    /**
     * 
     * @type {Array<CollectionVideoPostVO>}
     * @memberof ResponseListCollectionVideoPostVO
     */
    data?: Array<CollectionVideoPostVO>;
}

/**
 * Check if a given object implements the ResponseListCollectionVideoPostVO interface.
 */
export function instanceOfResponseListCollectionVideoPostVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseListCollectionVideoPostVOFromJSON(json: any): ResponseListCollectionVideoPostVO {
    return ResponseListCollectionVideoPostVOFromJSONTyped(json, false);
}

export function ResponseListCollectionVideoPostVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListCollectionVideoPostVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(CollectionVideoPostVOFromJSON)),
    };
}

export function ResponseListCollectionVideoPostVOToJSON(value?: ResponseListCollectionVideoPostVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(CollectionVideoPostVOToJSON)),
    };
}

