/* tslint:disable */
/* eslint-disable */
/**
 * service-collection
 * 收藏服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseBoolean
 */
export interface ResponseBoolean {
    /**
     * 
     * @type {number}
     * @memberof ResponseBoolean
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseBoolean
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResponseBoolean
     */
    data?: boolean;
}

/**
 * Check if a given object implements the ResponseBoolean interface.
 */
export function instanceOfResponseBoolean(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBooleanFromJSON(json: any): ResponseBoolean {
    return ResponseBooleanFromJSONTyped(json, false);
}

export function ResponseBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBoolean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function ResponseBooleanToJSON(value?: ResponseBoolean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': value.data,
    };
}

