/* tslint:disable */
/* eslint-disable */
/**
 * service-collection
 * 收藏服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CollectionGroupVO } from './CollectionGroupVO';
import {
    CollectionGroupVOFromJSON,
    CollectionGroupVOFromJSONTyped,
    CollectionGroupVOToJSON,
} from './CollectionGroupVO';

/**
 * 
 * @export
 * @interface ResponseListCollectionGroupVO
 */
export interface ResponseListCollectionGroupVO {
    /**
     * 
     * @type {number}
     * @memberof ResponseListCollectionGroupVO
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseListCollectionGroupVO
     */
    message?: string;
    /**
     * 
     * @type {Array<CollectionGroupVO>}
     * @memberof ResponseListCollectionGroupVO
     */
    data?: Array<CollectionGroupVO>;
}

/**
 * Check if a given object implements the ResponseListCollectionGroupVO interface.
 */
export function instanceOfResponseListCollectionGroupVO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseListCollectionGroupVOFromJSON(json: any): ResponseListCollectionGroupVO {
    return ResponseListCollectionGroupVOFromJSONTyped(json, false);
}

export function ResponseListCollectionGroupVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListCollectionGroupVO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(CollectionGroupVOFromJSON)),
    };
}

export function ResponseListCollectionGroupVOToJSON(value?: ResponseListCollectionGroupVO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(CollectionGroupVOToJSON)),
    };
}

