/* tslint:disable */
/* eslint-disable */
/**
 * service-danmaku
 * 弹幕服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResponseChatMessage,
  ResponseChatRoom,
  ResponseListChatMessage,
  SendDanmakuDTO,
} from '../models/index';
import {
    ResponseChatMessageFromJSON,
    ResponseChatMessageToJSON,
    ResponseChatRoomFromJSON,
    ResponseChatRoomToJSON,
    ResponseListChatMessageFromJSON,
    ResponseListChatMessageToJSON,
    SendDanmakuDTOFromJSON,
    SendDanmakuDTOToJSON,
} from '../models/index';

export interface GetChatRoomRequest {
    chatRoomId: number;
}

export interface GetChatRoomByVideoResourceIdRequest {
    videoResourceId: number;
}

export interface GetRecentDanmakuListRequest {
    chatRoomId: number;
    n?: number;
}

export interface SendDanmakuRequest {
    sendDanmakuDTO: SendDanmakuDTO;
}

/**
 * 
 */
export class DanmakuControllerApi extends runtime.BaseAPI {

    /**
     */
    async getChatRoomRaw(requestParameters: GetChatRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseChatRoom>> {
        if (requestParameters.chatRoomId === null || requestParameters.chatRoomId === undefined) {
            throw new runtime.RequiredError('chatRoomId','Required parameter requestParameters.chatRoomId was null or undefined when calling getChatRoom.');
        }

        const queryParameters: any = {};

        if (requestParameters.chatRoomId !== undefined) {
            queryParameters['chatRoomId'] = requestParameters.chatRoomId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/danmaku/getChatRoom`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseChatRoomFromJSON(jsonValue));
    }

    /**
     */
    async getChatRoom(requestParameters: GetChatRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseChatRoom> {
        const response = await this.getChatRoomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getChatRoomByVideoResourceIdRaw(requestParameters: GetChatRoomByVideoResourceIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseChatRoom>> {
        if (requestParameters.videoResourceId === null || requestParameters.videoResourceId === undefined) {
            throw new runtime.RequiredError('videoResourceId','Required parameter requestParameters.videoResourceId was null or undefined when calling getChatRoomByVideoResourceId.');
        }

        const queryParameters: any = {};

        if (requestParameters.videoResourceId !== undefined) {
            queryParameters['videoResourceId'] = requestParameters.videoResourceId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/danmaku/getChatRoomByVideoResourceId`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseChatRoomFromJSON(jsonValue));
    }

    /**
     */
    async getChatRoomByVideoResourceId(requestParameters: GetChatRoomByVideoResourceIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseChatRoom> {
        const response = await this.getChatRoomByVideoResourceIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getRecentDanmakuListRaw(requestParameters: GetRecentDanmakuListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseListChatMessage>> {
        if (requestParameters.chatRoomId === null || requestParameters.chatRoomId === undefined) {
            throw new runtime.RequiredError('chatRoomId','Required parameter requestParameters.chatRoomId was null or undefined when calling getRecentDanmakuList.');
        }

        const queryParameters: any = {};

        if (requestParameters.chatRoomId !== undefined) {
            queryParameters['chatRoomId'] = requestParameters.chatRoomId;
        }

        if (requestParameters.n !== undefined) {
            queryParameters['n'] = requestParameters.n;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/danmaku/getRecentDanmakuList`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseListChatMessageFromJSON(jsonValue));
    }

    /**
     */
    async getRecentDanmakuList(requestParameters: GetRecentDanmakuListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseListChatMessage> {
        const response = await this.getRecentDanmakuListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async sendDanmakuRaw(requestParameters: SendDanmakuRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseChatMessage>> {
        if (requestParameters.sendDanmakuDTO === null || requestParameters.sendDanmakuDTO === undefined) {
            throw new runtime.RequiredError('sendDanmakuDTO','Required parameter requestParameters.sendDanmakuDTO was null or undefined when calling sendDanmaku.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/danmaku/sendDanmaku`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendDanmakuDTOToJSON(requestParameters.sendDanmakuDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseChatMessageFromJSON(jsonValue));
    }

    /**
     */
    async sendDanmaku(requestParameters: SendDanmakuRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseChatMessage> {
        const response = await this.sendDanmakuRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
