/* tslint:disable */
/* eslint-disable */
/**
 * service-collection
 * 收藏服务API接口说明
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResponseBoolean,
  ResponseCollectionGroupVO,
  ResponseListCollectionGroupVO,
  ResponseListCollectionVideoPostVO,
  ResponseObject,
} from '../models/index';
import {
    ResponseBooleanFromJSON,
    ResponseBooleanToJSON,
    ResponseCollectionGroupVOFromJSON,
    ResponseCollectionGroupVOToJSON,
    ResponseListCollectionGroupVOFromJSON,
    ResponseListCollectionGroupVOToJSON,
    ResponseListCollectionVideoPostVOFromJSON,
    ResponseListCollectionVideoPostVOToJSON,
    ResponseObjectFromJSON,
    ResponseObjectToJSON,
} from '../models/index';

export interface AddCollectionVideoPostRequest {
    collectionGroupId: number;
    nkid: number;
}

export interface CreateCollectionGroupRequest {
    name: string;
    description?: string;
}

export interface DeleteCollectionGroupRequest {
    collectionGroupId: number;
}

export interface GetCollectionGroupsRequest {
    userId?: number;
}

export interface GetCollectionVideoPostsRequest {
    collectionGroupId: number;
    page?: number;
    pageSize?: number;
}

export interface RemoveCollectionVideoPostRequest {
    collectionGroupId: number;
    nkid: number;
}

export interface UpdateCollectionGroupRequest {
    collectionGroupId: number;
    name: string;
    description: string;
}

/**
 * 
 */
export class CollectionControllerApi extends runtime.BaseAPI {

    /**
     * 添加收藏
     */
    async addCollectionVideoPostRaw(requestParameters: AddCollectionVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseObject>> {
        if (requestParameters.collectionGroupId === null || requestParameters.collectionGroupId === undefined) {
            throw new runtime.RequiredError('collectionGroupId','Required parameter requestParameters.collectionGroupId was null or undefined when calling addCollectionVideoPost.');
        }

        if (requestParameters.nkid === null || requestParameters.nkid === undefined) {
            throw new runtime.RequiredError('nkid','Required parameter requestParameters.nkid was null or undefined when calling addCollectionVideoPost.');
        }

        const queryParameters: any = {};

        if (requestParameters.collectionGroupId !== undefined) {
            queryParameters['collectionGroupId'] = requestParameters.collectionGroupId;
        }

        if (requestParameters.nkid !== undefined) {
            queryParameters['nkid'] = requestParameters.nkid;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/collection/addCollectionVideoPost`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseObjectFromJSON(jsonValue));
    }

    /**
     * 添加收藏
     */
    async addCollectionVideoPost(requestParameters: AddCollectionVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseObject> {
        const response = await this.addCollectionVideoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 创建收藏夹
     */
    async createCollectionGroupRaw(requestParameters: CreateCollectionGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseCollectionGroupVO>> {
        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling createCollectionGroup.');
        }

        const queryParameters: any = {};

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.description !== undefined) {
            queryParameters['description'] = requestParameters.description;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/collection/createCollectionGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseCollectionGroupVOFromJSON(jsonValue));
    }

    /**
     * 创建收藏夹
     */
    async createCollectionGroup(requestParameters: CreateCollectionGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseCollectionGroupVO> {
        const response = await this.createCollectionGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 删除收藏夹
     */
    async deleteCollectionGroupRaw(requestParameters: DeleteCollectionGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseBoolean>> {
        if (requestParameters.collectionGroupId === null || requestParameters.collectionGroupId === undefined) {
            throw new runtime.RequiredError('collectionGroupId','Required parameter requestParameters.collectionGroupId was null or undefined when calling deleteCollectionGroup.');
        }

        const queryParameters: any = {};

        if (requestParameters.collectionGroupId !== undefined) {
            queryParameters['collectionGroupId'] = requestParameters.collectionGroupId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/collection/deleteCollectionGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseBooleanFromJSON(jsonValue));
    }

    /**
     * 删除收藏夹
     */
    async deleteCollectionGroup(requestParameters: DeleteCollectionGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseBoolean> {
        const response = await this.deleteCollectionGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 获取用户收藏夹列表
     */
    async getCollectionGroupsRaw(requestParameters: GetCollectionGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseListCollectionGroupVO>> {
        const queryParameters: any = {};

        if (requestParameters.userId !== undefined) {
            queryParameters['userId'] = requestParameters.userId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/collection/getCollectionGroups`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseListCollectionGroupVOFromJSON(jsonValue));
    }

    /**
     * 获取用户收藏夹列表
     */
    async getCollectionGroups(requestParameters: GetCollectionGroupsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseListCollectionGroupVO> {
        const response = await this.getCollectionGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 获取收藏夹内的视频列表
     */
    async getCollectionVideoPostsRaw(requestParameters: GetCollectionVideoPostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseListCollectionVideoPostVO>> {
        if (requestParameters.collectionGroupId === null || requestParameters.collectionGroupId === undefined) {
            throw new runtime.RequiredError('collectionGroupId','Required parameter requestParameters.collectionGroupId was null or undefined when calling getCollectionVideoPosts.');
        }

        const queryParameters: any = {};

        if (requestParameters.collectionGroupId !== undefined) {
            queryParameters['collectionGroupId'] = requestParameters.collectionGroupId;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['pageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/collection/getCollectionVideoPosts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseListCollectionVideoPostVOFromJSON(jsonValue));
    }

    /**
     * 获取收藏夹内的视频列表
     */
    async getCollectionVideoPosts(requestParameters: GetCollectionVideoPostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseListCollectionVideoPostVO> {
        const response = await this.getCollectionVideoPostsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 移除收藏
     */
    async removeCollectionVideoPostRaw(requestParameters: RemoveCollectionVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseObject>> {
        if (requestParameters.collectionGroupId === null || requestParameters.collectionGroupId === undefined) {
            throw new runtime.RequiredError('collectionGroupId','Required parameter requestParameters.collectionGroupId was null or undefined when calling removeCollectionVideoPost.');
        }

        if (requestParameters.nkid === null || requestParameters.nkid === undefined) {
            throw new runtime.RequiredError('nkid','Required parameter requestParameters.nkid was null or undefined when calling removeCollectionVideoPost.');
        }

        const queryParameters: any = {};

        if (requestParameters.collectionGroupId !== undefined) {
            queryParameters['collectionGroupId'] = requestParameters.collectionGroupId;
        }

        if (requestParameters.nkid !== undefined) {
            queryParameters['nkid'] = requestParameters.nkid;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/collection/removeCollectionVideoPost`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseObjectFromJSON(jsonValue));
    }

    /**
     * 移除收藏
     */
    async removeCollectionVideoPost(requestParameters: RemoveCollectionVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseObject> {
        const response = await this.removeCollectionVideoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新收藏夹信息
     */
    async updateCollectionGroupRaw(requestParameters: UpdateCollectionGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseCollectionGroupVO>> {
        if (requestParameters.collectionGroupId === null || requestParameters.collectionGroupId === undefined) {
            throw new runtime.RequiredError('collectionGroupId','Required parameter requestParameters.collectionGroupId was null or undefined when calling updateCollectionGroup.');
        }

        if (requestParameters.name === null || requestParameters.name === undefined) {
            throw new runtime.RequiredError('name','Required parameter requestParameters.name was null or undefined when calling updateCollectionGroup.');
        }

        if (requestParameters.description === null || requestParameters.description === undefined) {
            throw new runtime.RequiredError('description','Required parameter requestParameters.description was null or undefined when calling updateCollectionGroup.');
        }

        const queryParameters: any = {};

        if (requestParameters.collectionGroupId !== undefined) {
            queryParameters['collectionGroupId'] = requestParameters.collectionGroupId;
        }

        if (requestParameters.name !== undefined) {
            queryParameters['name'] = requestParameters.name;
        }

        if (requestParameters.description !== undefined) {
            queryParameters['description'] = requestParameters.description;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/collection/updateCollectionGroup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseCollectionGroupVOFromJSON(jsonValue));
    }

    /**
     * 更新收藏夹信息
     */
    async updateCollectionGroup(requestParameters: UpdateCollectionGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseCollectionGroupVO> {
        const response = await this.updateCollectionGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
